<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AreaSeeder extends Seeder
{

    public function run()
    {
        $areas = array(
            array('id' => '1','district_id' => '1','name' => 'Debidwar','bn_name' => 'দেবিদ্বার','code' => '1008','url' => 'debidwar.comilla.gov.bd'),
  array('id' => '2','district_id' => '1','name' => 'Barura','bn_name' => 'বরুড়া','code' => '1012','url' => 'barura.comilla.gov.bd'),
  array('id' => '3','district_id' => '1','name' => 'Brahmanpara','bn_name' => 'ব্রাহ্মণপাড়া','code' => '1004','url' => 'brahmanpara.comilla.gov.bd'),
  array('id' => '4','district_id' => '1','name' => 'Chandina','bn_name' => 'চান্দিনা','code' => '1011','url' => 'chandina.comilla.gov.bd'),
  array('id' => '5','district_id' => '1','name' => 'Chauddagram','bn_name' => 'চৌদ্দগ্রাম','code' => '1002','url' => 'chauddagram.comilla.gov.bd'),
  array('id' => '6','district_id' => '1','name' => 'Daudkandi','bn_name' => 'দাউদকান্দি','code' => '1010','url' => 'daudkandi.comilla.gov.bd'),
  array('id' => '7','district_id' => '1','name' => 'Homna','bn_name' => 'হোমনা','code' => '1013','url' => 'homna.comilla.gov.bd'),
  array('id' => '8','district_id' => '1','name' => 'Laksam','bn_name' => 'লাকসাম','code' => '1005','url' => 'laksam.comilla.gov.bd'),
  array('id' => '9','district_id' => '1','name' => 'Muradnagar','bn_name' => 'মুরাদনগর','code' => '1003','url' => 'muradnagar.comilla.gov.bd'),
  array('id' => '10','district_id' => '1','name' => 'Nangalkot','bn_name' => 'নাঙ্গলকোট','code' => '1006','url' => 'nangalkot.comilla.gov.bd'),
  array('id' => '11','district_id' => '1','name' => 'Comilla Sadar','bn_name' => 'কুমিল্লা সদর','code' => '1001','url' => 'comillasadar.comilla.gov.bd'),
  array('id' => '12','district_id' => '1','name' => 'Meghna','bn_name' => 'মেঘনা','code' => '1014','url' => 'meghna.comilla.gov.bd'),
  array('id' => '13','district_id' => '1','name' => 'Monohargonj','bn_name' => 'মনোহরগঞ্জ','code' => '1007','url' => 'monohargonj.comilla.gov.bd'),
  array('id' => '15','district_id' => '1','name' => 'Titas','bn_name' => 'তিতাস','code' => '1015','url' => 'titas.comilla.gov.bd'),
  array('id' => '16','district_id' => '1','name' => 'Burichang','bn_name' => 'বুড়িচং','code' => '1009','url' => 'burichang.comilla.gov.bd'),
  array('id' => '17','district_id' => '1','name' => 'Lalmai','bn_name' => 'লালমাই','code' => '1016','url' => 'lalmai.comilla.gov.bd'),
  array('id' => '18','district_id' => '2','name' => 'Chhagalnaiya','bn_name' => 'ছাগলনাইয়া','code' => '0604','url' => 'chhagalnaiya.feni.gov.bd'),
  array('id' => '19','district_id' => '2','name' => 'Feni Sadar','bn_name' => 'ফেনী সদর','code' => '0601','url' => 'sadar.feni.gov.bd'),
  array('id' => '20','district_id' => '2','name' => 'Sonagazi','bn_name' => 'সোনাগাজী','code' => '0606','url' => 'sonagazi.feni.gov.bd'),
  array('id' => '21','district_id' => '2','name' => 'Fulgazi','bn_name' => 'ফুলগাজী','code' => '0603','url' => 'fulgazi.feni.gov.bd'),
  array('id' => '22','district_id' => '2','name' => 'Parshuram','bn_name' => 'পরশুরাম','code' => '0602','url' => 'parshuram.feni.gov.bd'),
  array('id' => '23','district_id' => '2','name' => 'Daganbhuiyan','bn_name' => 'দাগনভূঞা','code' => '0605','url' => 'daganbhuiyan.feni.gov.bd'),
  array('id' => '24','district_id' => '3','name' => 'Brahmanbaria Sadar','bn_name' => 'ব্রাহ্মণবাড়িয়া সদর','code' => '1101','url' => 'sadar.brahmanbaria.gov.bd'),
  array('id' => '25','district_id' => '3','name' => 'Kasba','bn_name' => 'কসবা','code' => '1104','url' => 'kasba.brahmanbaria.gov.bd'),
  array('id' => '26','district_id' => '3','name' => 'Nasirnagar','bn_name' => 'নাসিরনগর','code' => '1108','url' => 'nasirnagar.brahmanbaria.gov.bd'),
  array('id' => '27','district_id' => '3','name' => 'Sarail','bn_name' => 'সরাইল','code' => '1109','url' => 'sarail.brahmanbaria.gov.bd'),
  array('id' => '28','district_id' => '3','name' => 'Ashuganj','bn_name' => 'আশুগঞ্জ','code' => '1106','url' => 'ashuganj.brahmanbaria.gov.bd'),
  array('id' => '29','district_id' => '3','name' => 'Akhaura','bn_name' => 'আখাউড়া','code' => '1102','url' => 'akhaura.brahmanbaria.gov.bd'),
  array('id' => '30','district_id' => '3','name' => 'Nabinagar','bn_name' => 'নবীনগর','code' => '1103','url' => 'nabinagar.brahmanbaria.gov.bd'),
  array('id' => '31','district_id' => '3','name' => 'Bancharampur','bn_name' => 'বাঞ্ছারামপুর','code' => '1107','url' => 'bancharampur.brahmanbaria.gov.bd'),
  array('id' => '32','district_id' => '3','name' => 'Bijoynagar','bn_name' => 'বিজয়নগর','code' => '1105','url' => 'bijoynagar.brahmanbaria.gov.bd    '),
  array('id' => '33','district_id' => '4','name' => 'Rangamati Sadar','bn_name' => 'রাঙ্গামাটি সদর','code' => '0401','url' => 'sadar.rangamati.gov.bd'),
  array('id' => '34','district_id' => '4','name' => 'Kaptai','bn_name' => 'কাপ্তাই','code' => '0402','url' => 'kaptai.rangamati.gov.bd'),
  array('id' => '35','district_id' => '4','name' => 'Kawkhali','bn_name' => 'কাউখালী','code' => '0406','url' => 'kawkhali.rangamati.gov.bd'),
  array('id' => '36','district_id' => '4','name' => 'Baghaichari','bn_name' => 'বাঘাইছড়ি','code' => '0410','url' => 'baghaichari.rangamati.gov.bd'),
  array('id' => '37','district_id' => '4','name' => 'Barkal','bn_name' => 'বরকল','code' => '0405','url' => 'barkal.rangamati.gov.bd'),
  array('id' => '38','district_id' => '4','name' => 'Langadu','bn_name' => 'লংগদু','code' => '0403','url' => 'langadu.rangamati.gov.bd'),
  array('id' => '39','district_id' => '4','name' => 'Rajasthali','bn_name' => 'রাজস্থলী','code' => '0408','url' => 'rajasthali.rangamati.gov.bd'),
  array('id' => '40','district_id' => '4','name' => 'Belaichari','bn_name' => 'বিলাইছড়ি','code' => '0409','url' => 'belaichari.rangamati.gov.bd'),
  array('id' => '41','district_id' => '4','name' => 'Juraichari','bn_name' => 'জুরাছড়ি','code' => '0411','url' => 'juraichari.rangamati.gov.bd'),
  array('id' => '42','district_id' => '4','name' => 'Naniarchar','bn_name' => 'নানিয়ারচর','code' => '0404','url' => 'naniarchar.rangamati.gov.bd'),
  array('id' => '43','district_id' => '5','name' => 'Noakhali Sadar','bn_name' => 'নোয়াখালী সদর','code' => '0801','url' => 'sadar.noakhali.gov.bd'),
  array('id' => '44','district_id' => '5','name' => 'Companiganj','bn_name' => 'কোম্পানীগঞ্জ','code' => '0805','url' => 'companiganj.noakhali.gov.bd'),
  array('id' => '45','district_id' => '5','name' => 'Begumganj','bn_name' => 'বেগমগঞ্জ','code' => '0804','url' => 'begumganj.noakhali.gov.bd'),
  array('id' => '46','district_id' => '5','name' => 'Hatia','bn_name' => 'হাতিয়া','code' => '0807','url' => 'hatia.noakhali.gov.bd'),
  array('id' => '47','district_id' => '5','name' => 'Subarnachar','bn_name' => 'সুবর্ণচর','code' => '0806','url' => 'subarnachar.noakhali.gov.bd'),
  array('id' => '48','district_id' => '5','name' => 'Kabirhat','bn_name' => 'কবিরহাট','code' => '0809','url' => 'kabirhat.noakhali.gov.bd'),
  array('id' => '49','district_id' => '5','name' => 'Senbug','bn_name' => 'সেনবাগ','code' => '0803','url' => 'senbug.noakhali.gov.bd'),
  array('id' => '50','district_id' => '5','name' => 'Chatkhil','bn_name' => 'চাটখিল','code' => '0802','url' => 'chatkhil.noakhali.gov.bd'),
  array('id' => '51','district_id' => '5','name' => 'Sonaimori','bn_name' => 'সোনাইমুড়ী','code' => '0808','url' => 'sonaimori.noakhali.gov.bd'),
  array('id' => '52','district_id' => '6','name' => 'Haimchar','bn_name' => 'হাইমচর','code' => '0906','url' => 'haimchar.chandpur.gov.bd'),
  array('id' => '53','district_id' => '6','name' => 'Kachua','bn_name' => 'কচুয়া','code' => '0904','url' => 'kachua.chandpur.gov.bd'),
  array('id' => '54','district_id' => '6','name' => 'Shahrasti','bn_name' => 'শাহরাস্তি','code' => '0905','url' => 'shahrasti.chandpur.gov.bd'),
  array('id' => '55','district_id' => '6','name' => 'Chandpur Sadar','bn_name' => 'চাঁদপুর সদর','code' => '0901','url' => 'sadar.chandpur.gov.bd'),
  array('id' => '56','district_id' => '6','name' => 'Matlab South','bn_name' => 'মতলব দক্ষিণ','code' => '0908','url' => 'matlabsouth.chandpur.gov.bd'),
  array('id' => '57','district_id' => '6','name' => 'Hajiganj','bn_name' => 'হাজীগঞ্জ','code' => '0902','url' => 'hajiganj.chandpur.gov.bd'),
  array('id' => '58','district_id' => '6','name' => 'Matlab North','bn_name' => 'মতলব উত্তর','code' => '0907','url' => 'matlabnorth.chandpur.gov.bd'),
  array('id' => '59','district_id' => '6','name' => 'Faridgonj','bn_name' => 'ফরিদগঞ্জ','code' => '0903','url' => 'faridgonj.chandpur.gov.bd'),
  array('id' => '60','district_id' => '7','name' => 'Lakshmipur Sadar','bn_name' => 'লক্ষ্মীপুর সদর','code' => '0701','url' => 'sadar.lakshmipur.gov.bd'),
  array('id' => '61','district_id' => '7','name' => 'Kamalnagar','bn_name' => 'কমলনগর','code' => '0704','url' => 'kamalnagar.lakshmipur.gov.bd'),
  array('id' => '62','district_id' => '7','name' => 'Raipur','bn_name' => 'রায়পুর','code' => '0703','url' => 'raipur.lakshmipur.gov.bd'),
  array('id' => '63','district_id' => '7','name' => 'Ramgati','bn_name' => 'রামগতি','code' => '0705','url' => 'ramgati.lakshmipur.gov.bd'),
  array('id' => '64','district_id' => '7','name' => 'Ramganj','bn_name' => 'রামগঞ্জ','code' => '0702','url' => 'ramganj.lakshmipur.gov.bd'),
  array('id' => '65','district_id' => '8','name' => 'Rangunia','bn_name' => 'রাঙ্গুনিয়া','code' => '0106','url' => 'rangunia.chittagong.gov.bd'),
  array('id' => '66','district_id' => '8','name' => 'Sitakunda','bn_name' => 'সীতাকুন্ড','code' => '0107','url' => 'sitakunda.chittagong.gov.bd'),
  array('id' => '67','district_id' => '8','name' => 'Mirsharai','bn_name' => 'মীরসরাই','code' => '0108','url' => 'mirsharai.chittagong.gov.bd'),
  array('id' => '68','district_id' => '8','name' => 'Patiya','bn_name' => 'পটিয়া','code' => '0110','url' => 'patiya.chittagong.gov.bd'),
  array('id' => '69','district_id' => '8','name' => 'Sandwip','bn_name' => 'ডবলমুরিং','code' => '0118','url' => 'sandwip.chittagong.gov.bd'),
  array('id' => '70','district_id' => '8','name' => 'Banshkhali','bn_name' => 'বাঁশখালী','code' => '0114','url' => 'banshkhali.chittagong.gov.bd'),
  array('id' => '71','district_id' => '8','name' => 'Boalkhali','bn_name' => 'বোয়ালখালী','code' => '0109','url' => 'boalkhali.chittagong.gov.bd'),
  array('id' => '72','district_id' => '8','name' => 'Anwara','bn_name' => 'আনোয়ারা','code' => '0115','url' => 'anwara.chittagong.gov.bd'),
  array('id' => '73','district_id' => '8','name' => 'Chandanaish','bn_name' => 'চন্দনাইশ','code' => '0111','url' => 'chandanaish.chittagong.gov.bd'),
  array('id' => '74','district_id' => '8','name' => 'Satkania','bn_name' => 'সাতকানিয়া','code' => '0112','url' => 'satkania.chittagong.gov.bd'),
  array('id' => '75','district_id' => '8','name' => 'Lohagara','bn_name' => 'লোহাগাড়া','code' => '0113','url' => 'lohagara.chittagong.gov.bd'),
  array('id' => '76','district_id' => '8','name' => 'Hathazari','bn_name' => 'হাটহাজারী','code' => '0102','url' => 'hathazari.chittagong.gov.bd'),
  array('id' => '77','district_id' => '8','name' => 'Fatikchhari','bn_name' => 'ফটিকছড়ি','code' => '0103','url' => 'fatikchhari.chittagong.gov.bd'),
  array('id' => '78','district_id' => '8','name' => 'Raozan','bn_name' => 'রাউজান','code' => '0105','url' => 'raozan.chittagong.gov.bd'),
  array('id' => '79','district_id' => '8','name' => 'Karnafuli','bn_name' => 'কর্ণফুলী','code' => '0116','url' => 'karnafuli.chittagong.gov.bd'),
  array('id' => '80','district_id' => '9','name' => 'Coxsbazar Sadar','bn_name' => 'কক্সবাজার সদর','code' => '0201','url' => 'sadar.coxsbazar.gov.bd'),
  array('id' => '81','district_id' => '9','name' => 'Chakaria','bn_name' => 'চকরিয়া','code' => '0203','url' => 'chakaria.coxsbazar.gov.bd'),
  array('id' => '82','district_id' => '9','name' => 'Kutubdia','bn_name' => 'কুতুবদিয়া','code' => '0206','url' => 'kutubdia.coxsbazar.gov.bd'),
  array('id' => '83','district_id' => '9','name' => 'Ukhiya','bn_name' => 'উখিয়া','code' => '0207','url' => 'ukhiya.coxsbazar.gov.bd'),
  array('id' => '84','district_id' => '9','name' => 'Moheshkhali','bn_name' => 'মহেশখালী','code' => '0205','url' => 'moheshkhali.coxsbazar.gov.bd'),
  array('id' => '85','district_id' => '9','name' => 'Pekua','bn_name' => 'পেকুয়া','code' => '0204','url' => 'pekua.coxsbazar.gov.bd'),
  array('id' => '86','district_id' => '9','name' => 'Ramu','bn_name' => 'রামু','code' => '0202','url' => 'ramu.coxsbazar.gov.bd'),
  array('id' => '87','district_id' => '9','name' => 'Teknaf','bn_name' => 'টেকনাফ','code' => '0208','url' => 'teknaf.coxsbazar.gov.bd'),
  array('id' => '88','district_id' => '10','name' => 'Khagrachhari Sadar','bn_name' => 'খাগড়াছড়ি সদর','code' => '0501','url' => 'sadar.khagrachhari.gov.bd'),
  array('id' => '89','district_id' => '10','name' => 'Dighinala','bn_name' => 'দিঘীনালা','code' => '0506','url' => 'dighinala.khagrachhari.gov.bd'),
  array('id' => '90','district_id' => '10','name' => 'Panchari','bn_name' => 'পানছড়ি','code' => '0504','url' => 'panchari.khagrachhari.gov.bd'),
  array('id' => '91','district_id' => '10','name' => 'Laxmichhari','bn_name' => 'লক্ষীছড়ি','code' => '0508','url' => 'laxmichhari.khagrachhari.gov.bd'),
  array('id' => '92','district_id' => '10','name' => 'Mohalchari','bn_name' => 'মহালছড়ি','code' => '0507','url' => 'mohalchari.khagrachhari.gov.bd'),
  array('id' => '93','district_id' => '10','name' => 'Manikchari','bn_name' => 'মানিকছড়ি','code' => '0503','url' => 'manikchari.khagrachhari.gov.bd'),
  array('id' => '94','district_id' => '10','name' => 'Ramgarh','bn_name' => 'রামগড়','code' => '0502','url' => 'ramgarh.khagrachhari.gov.bd'),
  array('id' => '95','district_id' => '10','name' => 'Matiranga','bn_name' => 'মাটিরাঙ্গা','code' => '0505','url' => 'matiranga.khagrachhari.gov.bd'),
  array('id' => '96','district_id' => '10','name' => 'Guimara','bn_name' => 'গুইমারা','code' => '0509','url' => 'guimara.khagrachhari.gov.bd'),
  array('id' => '97','district_id' => '11','name' => 'Bandarban Sadar','bn_name' => 'বান্দরবান সদর','code' => '0301','url' => 'sadar.bandarban.gov.bd'),
  array('id' => '98','district_id' => '11','name' => 'Alikadam','bn_name' => 'আলীকদম','code' => '0304','url' => 'alikadam.bandarban.gov.bd'),
  array('id' => '99','district_id' => '11','name' => 'Naikhongchhari','bn_name' => 'নাইক্ষ্যংছড়ি','code' => '0303','url' => 'naikhongchhari.bandarban.gov.bd'),
  array('id' => '100','district_id' => '11','name' => 'Rowangchhari','bn_name' => 'রোয়াংছড়ি','code' => '0308','url' => 'rowangchhari.bandarban.gov.bd'),
  array('id' => '101','district_id' => '11','name' => 'Lama','bn_name' => 'লামা','code' => '0302','url' => 'lama.bandarban.gov.bd'),
  array('id' => '102','district_id' => '11','name' => 'Ruma','bn_name' => 'রুমা','code' => '0305','url' => 'ruma.bandarban.gov.bd'),
  array('id' => '103','district_id' => '11','name' => 'Thanchi','bn_name' => 'থানচি','code' => '0306','url' => 'thanchi.bandarban.gov.bd'),
  array('id' => '104','district_id' => '12','name' => 'Belkuchi','bn_name' => 'বেলকুচি','code' => '3907','url' => 'belkuchi.sirajganj.gov.bd'),
  array('id' => '105','district_id' => '12','name' => 'Chauhali','bn_name' => 'চৌহালি','code' => '3908','url' => 'chauhali.sirajganj.gov.bd'),
  array('id' => '106','district_id' => '12','name' => 'Kamarkhand','bn_name' => 'কামারখন্দ','code' => '3905','url' => 'kamarkhand.sirajganj.gov.bd'),
  array('id' => '107','district_id' => '12','name' => 'Kazipur','bn_name' => 'কাজীপুর','code' => '3902','url' => 'kazipur.sirajganj.gov.bd'),
  array('id' => '108','district_id' => '12','name' => 'Raigonj','bn_name' => 'রায়গঞ্জ','code' => '3903','url' => 'raigonj.sirajganj.gov.bd'),
  array('id' => '109','district_id' => '12','name' => 'Shahjadpur','bn_name' => 'শাহজাদপুর','code' => '3909','url' => 'shahjadpur.sirajganj.gov.bd'),
  array('id' => '110','district_id' => '12','name' => 'Sirajganj Sadar','bn_name' => 'সিরাজগঞ্জ সদর','code' => '3901','url' => 'sirajganjsadar.sirajganj.gov.bd'),
  array('id' => '111','district_id' => '12','name' => 'Tarash','bn_name' => 'তাড়াশ','code' => '3904','url' => 'tarash.sirajganj.gov.bd'),
  array('id' => '112','district_id' => '12','name' => 'Ullapara','bn_name' => 'উল্লাপাড়া','code' => '3906','url' => 'ullapara.sirajganj.gov.bd'),
  array('id' => '113','district_id' => '13','name' => 'Sujanagar','bn_name' => 'সুজানগর','code' => '4009','url' => 'sujanagar.pabna.gov.bd'),
  array('id' => '114','district_id' => '13','name' => 'Ishurdi','bn_name' => 'ঈশ্বরদী','code' => '4006','url' => 'ishurdi.pabna.gov.bd'),
  array('id' => '115','district_id' => '13','name' => 'Bhangura','bn_name' => 'ভাঙ্গুড়া','code' => '4003','url' => 'bhangura.pabna.gov.bd'),
  array('id' => '116','district_id' => '13','name' => 'Pabna Sadar','bn_name' => 'পাবনা সদর','code' => '4001','url' => 'pabnasadar.pabna.gov.bd'),
  array('id' => '117','district_id' => '13','name' => 'Bera','bn_name' => 'বেড়া','code' => '4008','url' => 'bera.pabna.gov.bd'),
  array('id' => '118','district_id' => '13','name' => 'Atghoria','bn_name' => 'আটঘরিয়া','code' => '4005','url' => 'atghoria.pabna.gov.bd'),
  array('id' => '119','district_id' => '13','name' => 'Chatmohar','bn_name' => 'চাটমোহর','code' => '4002','url' => 'chatmohar.pabna.gov.bd'),
  array('id' => '120','district_id' => '13','name' => 'Santhia','bn_name' => 'সাঁথিয়া','code' => '4007','url' => 'santhia.pabna.gov.bd'),
  array('id' => '121','district_id' => '13','name' => 'Faridpur','bn_name' => 'ফরিদপুর','code' => '4004','url' => 'faridpur.pabna.gov.bd'),
  array('id' => '122','district_id' => '14','name' => 'Kahaloo','bn_name' => 'কাহালু','code' => '3707','url' => 'kahaloo.bogra.gov.bd'),
  array('id' => '123','district_id' => '14','name' => 'Bogra Sadar','bn_name' => 'বগুড়া সদর','code' => '3701','url' => 'sadar.bogra.gov.bd'),
  array('id' => '124','district_id' => '14','name' => 'Shariakandi','bn_name' => 'সারিয়াকান্দি','code' => '3706','url' => 'shariakandi.bogra.gov.bd'),
  array('id' => '125','district_id' => '14','name' => 'Shajahanpur','bn_name' => 'শাজাহানপুর','code' => '3713','url' => 'shajahanpur.bogra.gov.bd'),
  array('id' => '126','district_id' => '14','name' => 'Dupchanchia','bn_name' => 'ধুপচাঁচিয়া','code' => '3705','url' => 'dupchanchia.bogra.gov.bd'),
  array('id' => '127','district_id' => '14','name' => 'Adamdighi','bn_name' => 'আদমদিঘি','code' => '3702','url' => 'adamdighi.bogra.gov.bd'),
  array('id' => '128','district_id' => '14','name' => 'Nondigram','bn_name' => 'নন্দিগ্রাম','code' => '3710','url' => 'nondigram.bogra.gov.bd'),
  array('id' => '129','district_id' => '14','name' => 'Sonatala','bn_name' => 'সোনাতলা','code' => '3709','url' => 'sonatala.bogra.gov.bd'),
  array('id' => '130','district_id' => '14','name' => 'Dhunot','bn_name' => 'ধুনট','code' => '3703','url' => 'dhunot.bogra.gov.bd'),
  array('id' => '131','district_id' => '14','name' => 'Gabtali','bn_name' => 'গাবতলী','code' => '3704','url' => 'gabtali.bogra.gov.bd'),
  array('id' => '132','district_id' => '14','name' => 'Sherpur','bn_name' => 'শেরপুর','code' => '3711','url' => 'sherpur.bogra.gov.bd'),
  array('id' => '133','district_id' => '14','name' => 'Shibganj','bn_name' => 'শিবগঞ্জ','code' => '3708','url' => 'shibganj.bogra.gov.bd'),
  array('id' => '134','district_id' => '15','name' => 'Paba','bn_name' => 'পবা','code' => '3306','url' => 'paba.rajshahi.gov.bd'),
  array('id' => '135','district_id' => '15','name' => 'Durgapur','bn_name' => 'দুর্গাপুর','code' => '3307','url' => 'durgapur.rajshahi.gov.bd'),
  array('id' => '136','district_id' => '15','name' => 'Mohonpur','bn_name' => 'মোহনপুর','code' => '3304','url' => 'mohonpur.rajshahi.gov.bd'),
  array('id' => '137','district_id' => '15','name' => 'Charghat','bn_name' => 'চারঘাট','code' => '3309','url' => 'charghat.rajshahi.gov.bd'),
  array('id' => '138','district_id' => '15','name' => 'Puthia','bn_name' => 'পুঠিয়া','code' => '3308','url' => 'puthia.rajshahi.gov.bd'),
  array('id' => '139','district_id' => '15','name' => 'Bagha','bn_name' => 'বাঘা','code' => '3310','url' => 'bagha.rajshahi.gov.bd'),
  array('id' => '140','district_id' => '15','name' => 'Godagari','bn_name' => 'গোদাগাড়ী','code' => '3305','url' => 'godagari.rajshahi.gov.bd'),
  array('id' => '141','district_id' => '15','name' => 'Tanore','bn_name' => 'তানোর','code' => '3302','url' => 'tanore.rajshahi.gov.bd'),
  array('id' => '142','district_id' => '15','name' => 'Bagmara','bn_name' => 'বাগমারা','code' => '3303','url' => 'bagmara.rajshahi.gov.bd'),
  array('id' => '143','district_id' => '16','name' => 'Natore Sadar','bn_name' => 'নাটোর সদর','code' => '3801','url' => 'natoresadar.natore.gov.bd'),
  array('id' => '144','district_id' => '16','name' => 'Singra','bn_name' => 'সিংড়া','code' => '3802','url' => 'singra.natore.gov.bd'),
  array('id' => '145','district_id' => '16','name' => 'Baraigram','bn_name' => 'বড়াইগ্রাম','code' => '3804','url' => 'baraigram.natore.gov.bd'),
  array('id' => '146','district_id' => '16','name' => 'Bagatipara','bn_name' => 'বাগাতিপাড়া','code' => '3805','url' => 'bagatipara.natore.gov.bd'),
  array('id' => '147','district_id' => '16','name' => 'Lalpur','bn_name' => 'লালপুর','code' => '3806','url' => 'lalpur.natore.gov.bd'),
  array('id' => '148','district_id' => '16','name' => 'Gurudaspur','bn_name' => 'গুরুদাসপুর','code' => '3803','url' => 'gurudaspur.natore.gov.bd'),
  array('id' => '149','district_id' => '16','name' => 'Naldanga','bn_name' => 'নলডাঙ্গা','code' => '3807','url' => 'naldanga.natore.gov.bd'),
  array('id' => '150','district_id' => '17','name' => 'Akkelpur','bn_name' => 'আক্কেলপুর','code' => '3605','url' => 'akkelpur.joypurhat.gov.bd'),
  array('id' => '151','district_id' => '17','name' => 'Kalai','bn_name' => 'কালাই','code' => '3603','url' => 'kalai.joypurhat.gov.bd'),
  array('id' => '152','district_id' => '17','name' => 'Khetlal','bn_name' => 'ক্ষেতলাল','code' => '3604','url' => 'khetlal.joypurhat.gov.bd'),
  array('id' => '153','district_id' => '17','name' => 'Panchbibi','bn_name' => 'পাঁচবিবি','code' => '3602','url' => 'panchbibi.joypurhat.gov.bd'),
  array('id' => '154','district_id' => '17','name' => 'Joypurhat Sadar','bn_name' => 'জয়পুরহাট সদর','code' => '3601','url' => 'joypurhatsadar.joypurhat.gov.bd'),
  array('id' => '155','district_id' => '18','name' => 'Chapainawabganj Sadar','bn_name' => 'চাঁপাইনবাবগঞ্জ সদর','code' => '3401','url' => 'chapainawabganjsadar.chapainawabganj.gov.bd'),
  array('id' => '156','district_id' => '18','name' => 'Gomostapur','bn_name' => 'গোমস্তাপুর','code' => '3405','url' => 'gomostapur.chapainawabganj.gov.bd'),
  array('id' => '157','district_id' => '18','name' => 'Nachol','bn_name' => 'নাচোল','code' => '3403','url' => 'nachol.chapainawabganj.gov.bd'),
  array('id' => '158','district_id' => '18','name' => 'Bholahat','bn_name' => 'ভোলাহাট','code' => '3402','url' => 'bholahat.chapainawabganj.gov.bd'),
  array('id' => '159','district_id' => '18','name' => 'Shibganj','bn_name' => 'শিবগঞ্জ','code' => '3404','url' => 'shibganj.chapainawabganj.gov.bd'),
  array('id' => '160','district_id' => '19','name' => 'Mohadevpur','bn_name' => 'মহাদেবপুর','code' => '3504','url' => 'mohadevpur.naogaon.gov.bd'),
  array('id' => '161','district_id' => '19','name' => 'Badalgachi','bn_name' => 'বদলগাছী','code' => '3508','url' => 'badalgachi.naogaon.gov.bd'),
  array('id' => '162','district_id' => '19','name' => 'Patnitala','bn_name' => 'পত্নিতলা','code' => '3507','url' => 'patnitala.naogaon.gov.bd'),
  array('id' => '163','district_id' => '19','name' => 'Dhamoirhat','bn_name' => 'ধামইরহাট','code' => '3506','url' => 'dhamoirhat.naogaon.gov.bd'),
  array('id' => '164','district_id' => '19','name' => 'Niamatpur','bn_name' => 'নিয়ামতপুর','code' => '3509','url' => 'niamatpur.naogaon.gov.bd'),
  array('id' => '165','district_id' => '19','name' => 'Manda','bn_name' => 'মান্দা','code' => '3510','url' => 'manda.naogaon.gov.bd'),
  array('id' => '166','district_id' => '19','name' => 'Atrai','bn_name' => 'আত্রাই','code' => '3511','url' => 'atrai.naogaon.gov.bd'),
  array('id' => '167','district_id' => '19','name' => 'Raninagar','bn_name' => 'রাণীনগর','code' => '3502','url' => 'raninagar.naogaon.gov.bd'),
  array('id' => '168','district_id' => '19','name' => 'Naogaon Sadar','bn_name' => 'নওগাঁ সদর','code' => '3501','url' => 'naogaonsadar.naogaon.gov.bd'),
  array('id' => '169','district_id' => '19','name' => 'Porsha','bn_name' => 'পোরশা','code' => '3503','url' => 'porsha.naogaon.gov.bd'),
  array('id' => '170','district_id' => '19','name' => 'Sapahar','bn_name' => 'সাপাহার','code' => '3505','url' => 'sapahar.naogaon.gov.bd'),
  array('id' => '171','district_id' => '20','name' => 'Manirampur','bn_name' => 'মণিরামপুর','code' => '5206','url' => 'manirampur.jessore.gov.bd'),
  array('id' => '172','district_id' => '20','name' => 'Abhaynagar','bn_name' => 'অভয়নগর','code' => '5207','url' => 'abhaynagar.jessore.gov.bd'),
  array('id' => '173','district_id' => '20','name' => 'Bagherpara','bn_name' => 'বাঘারপাড়া','code' => '5203','url' => 'bagherpara.jessore.gov.bd'),
  array('id' => '174','district_id' => '20','name' => 'Chougachha','bn_name' => 'চৌগাছা','code' => '5202','url' => 'chougachha.jessore.gov.bd'),
  array('id' => '175','district_id' => '20','name' => 'Jhikargacha','bn_name' => 'ঝিকরগাছা','code' => '5204','url' => 'jhikargacha.jessore.gov.bd'),
  array('id' => '176','district_id' => '20','name' => 'Keshabpur','bn_name' => 'কেশবপুর','code' => '5208','url' => 'keshabpur.jessore.gov.bd'),
  array('id' => '177','district_id' => '20','name' => 'Jessore Sadar','bn_name' => 'যশোর সদর','code' => '5201','url' => 'sadar.jessore.gov.bd'),
  array('id' => '178','district_id' => '20','name' => 'Sharsha','bn_name' => 'শার্শা','code' => '5205','url' => 'sharsha.jessore.gov.bd'),
  array('id' => '179','district_id' => '21','name' => 'Assasuni','bn_name' => 'আশাশুনি','code' => '5503','url' => 'assasuni.satkhira.gov.bd'),
  array('id' => '180','district_id' => '21','name' => 'Debhata','bn_name' => 'দেবহাটা','code' => '5508','url' => 'debhata.satkhira.gov.bd'),
  array('id' => '181','district_id' => '21','name' => 'Kalaroa','bn_name' => 'কলারোয়া','code' => '5507','url' => 'kalaroa.satkhira.gov.bd'),
  array('id' => '182','district_id' => '21','name' => 'Satkhira Sadar','bn_name' => 'সাতক্ষীরা সদর','code' => '5501','url' => 'satkhirasadar.satkhira.gov.bd'),
  array('id' => '183','district_id' => '21','name' => 'Shyamnagar','bn_name' => 'শ্যামনগর','code' => '5506','url' => 'shyamnagar.satkhira.gov.bd'),
  array('id' => '184','district_id' => '21','name' => 'Tala','bn_name' => 'তালা','code' => '5502','url' => 'tala.satkhira.gov.bd'),
  array('id' => '185','district_id' => '21','name' => 'Kaliganj','bn_name' => 'কালিগঞ্জ','code' => '5504','url' => 'kaliganj.satkhira.gov.bd'),
  array('id' => '186','district_id' => '22','name' => 'Mujibnagar','bn_name' => 'মুজিবনগর','code' => '5803','url' => 'mujibnagar.meherpur.gov.bd'),
  array('id' => '187','district_id' => '22','name' => 'Meherpur Sadar','bn_name' => 'মেহেরপুর সদর','code' => '5801','url' => 'meherpursadar.meherpur.gov.bd'),
  array('id' => '188','district_id' => '22','name' => 'Gangni','bn_name' => 'গাংনী','code' => '5802','url' => 'gangni.meherpur.gov.bd'),
  array('id' => '189','district_id' => '23','name' => 'Narail Sadar','bn_name' => 'নড়াইল সদর','code' => '5701','url' => 'narailsadar.narail.gov.bd'),
  array('id' => '190','district_id' => '23','name' => 'Lohagara','bn_name' => 'লোহাগড়া','code' => '5702','url' => 'lohagara.narail.gov.bd'),
  array('id' => '191','district_id' => '23','name' => 'Kalia','bn_name' => 'কালিয়া','code' => '5703','url' => 'kalia.narail.gov.bd'),
  array('id' => '192','district_id' => '24','name' => 'Chuadanga Sadar','bn_name' => 'চুয়াডাঙ্গা সদর','code' => '5101','url' => 'chuadangasadar.chuadanga.gov.bd'),
  array('id' => '193','district_id' => '24','name' => 'Alamdanga','bn_name' => 'আলমডাঙ্গা','code' => '5102','url' => 'alamdanga.chuadanga.gov.bd'),
  array('id' => '194','district_id' => '24','name' => 'Damurhuda','bn_name' => 'দামুড়হুদা','code' => '5103','url' => 'damurhuda.chuadanga.gov.bd'),
  array('id' => '195','district_id' => '24','name' => 'Jibannagar','bn_name' => 'জীবননগর','code' => '5104','url' => 'jibannagar.chuadanga.gov.bd'),
  array('id' => '196','district_id' => '25','name' => 'Kushtia Sadar','bn_name' => 'কুষ্টিয়া সদর','code' => '5401','url' => 'kushtiasadar.kushtia.gov.bd'),
  array('id' => '197','district_id' => '25','name' => 'Kumarkhali','bn_name' => 'কুমারখালী','code' => '5405','url' => 'kumarkhali.kushtia.gov.bd'),
  array('id' => '198','district_id' => '25','name' => 'Khoksa','bn_name' => 'খোকসা','code' => '5406','url' => 'khoksa.kushtia.gov.bd'),
  array('id' => '199','district_id' => '25','name' => 'Mirpur','bn_name' => 'মিরপুর','code' => '5404','url' => 'mirpurkushtia.kushtia.gov.bd'),
  array('id' => '200','district_id' => '25','name' => 'Daulatpur','bn_name' => 'দৌলতপুর','code' => '5403','url' => 'daulatpur.kushtia.gov.bd'),
  array('id' => '201','district_id' => '25','name' => 'Bheramara','bn_name' => 'ভেড়ামারা','code' => '5402','url' => 'bheramara.kushtia.gov.bd'),
  array('id' => '202','district_id' => '26','name' => 'Shalikha','bn_name' => 'শালিখা','code' => '5602','url' => 'shalikha.magura.gov.bd'),
  array('id' => '203','district_id' => '26','name' => 'Sreepur','bn_name' => 'শ্রীপুর','code' => '5605','url' => 'sreepur.magura.gov.bd'),
  array('id' => '204','district_id' => '26','name' => 'Magura Sadar','bn_name' => 'মাগুরা সদর','code' => '5601','url' => 'magurasadar.magura.gov.bd'),
  array('id' => '205','district_id' => '26','name' => 'Mohammadpur','bn_name' => 'মুহাম্মদপুর','code' => '5603','url' => 'mohammadpur.magura.gov.bd'),
  array('id' => '206','district_id' => '27','name' => 'Paikgasa','bn_name' => 'পাইকগাছা','code' => '4907','url' => 'paikgasa.khulna.gov.bd'),
  array('id' => '207','district_id' => '27','name' => 'Fultola','bn_name' => 'ফুলতলা','code' => '4902','url' => 'fultola.khulna.gov.bd'),
  array('id' => '208','district_id' => '27','name' => 'Digholia','bn_name' => 'দিঘলিয়া','code' => '4915','url' => 'digholia.khulna.gov.bd'),
  array('id' => '209','district_id' => '27','name' => 'Rupsha','bn_name' => 'রূপসা','code' => '4910','url' => 'rupsha.khulna.gov.bd'),
  array('id' => '210','district_id' => '27','name' => 'Terokhada','bn_name' => 'তেরখাদা','code' => '4913','url' => 'terokhada.khulna.gov.bd'),
  array('id' => '211','district_id' => '27','name' => 'Dumuria','bn_name' => 'ডুমুরিয়া','code' => '4905','url' => 'dumuria.khulna.gov.bd'),
  array('id' => '212','district_id' => '27','name' => 'Botiaghata','bn_name' => 'বটিয়াঘাটা','code' => '4906','url' => 'botiaghata.khulna.gov.bd'),
  array('id' => '213','district_id' => '27','name' => 'Dakop','bn_name' => 'দাকোপ','code' => '4908','url' => 'dakop.khulna.gov.bd'),
  array('id' => '214','district_id' => '27','name' => 'Koyra','bn_name' => 'কয়রা','code' => '4909','url' => 'koyra.khulna.gov.bd'),
  array('id' => '215','district_id' => '28','name' => 'Fakirhat','bn_name' => 'ফকিরহাট','code' => '5004','url' => 'fakirhat.bagerhat.gov.bd'),
  array('id' => '216','district_id' => '28','name' => 'Bagerhat Sadar','bn_name' => 'বাগেরহাট সদর','code' => '5001','url' => 'sadar.bagerhat.gov.bd'),
  array('id' => '217','district_id' => '28','name' => 'Mollahat','bn_name' => 'মোল্লাহাট','code' => '5002','url' => 'mollahat.bagerhat.gov.bd'),
  array('id' => '218','district_id' => '28','name' => 'Sarankhola','bn_name' => 'শরণখোলা','code' => '5009','url' => 'sarankhola.bagerhat.gov.bd'),
  array('id' => '219','district_id' => '28','name' => 'Rampal','bn_name' => 'রামপাল','code' => '5005','url' => 'rampal.bagerhat.gov.bd'),
  array('id' => '220','district_id' => '28','name' => 'Morrelganj','bn_name' => 'মোড়েলগঞ্জ','code' => '5007','url' => 'morrelganj.bagerhat.gov.bd'),
  array('id' => '221','district_id' => '28','name' => 'Kachua','bn_name' => 'কচুয়া','code' => '5008','url' => 'kachua.bagerhat.gov.bd'),
  array('id' => '222','district_id' => '28','name' => 'Mongla','bn_name' => 'মংলা','code' => '5006','url' => 'mongla.bagerhat.gov.bd'),
  array('id' => '223','district_id' => '28','name' => 'Chitalmari','bn_name' => 'চিতলমারী','code' => '5003','url' => 'chitalmari.bagerhat.gov.bd'),
  array('id' => '224','district_id' => '29','name' => 'Jhenaidah Sadar','bn_name' => 'ঝিনাইদহ সদর','code' => '5301','url' => 'sadar.jhenaidah.gov.bd'),
  array('id' => '225','district_id' => '29','name' => 'Shailkupa','bn_name' => 'শৈলকুপা','code' => '5302','url' => 'shailkupa.jhenaidah.gov.bd'),
  array('id' => '226','district_id' => '29','name' => 'Harinakundu','bn_name' => 'হরিণাকুন্ড','code' => '5303','url' => 'harinakundu.jhenaidah.gov.bd'),
  array('id' => '227','district_id' => '29','name' => 'Kaliganj','bn_name' => 'কালীগঞ্জ','code' => '5305','url' => 'kaliganj.jhenaidah.gov.bd'),
  array('id' => '228','district_id' => '29','name' => 'Kotchandpur','bn_name' => 'কোটচাঁদপুর','code' => '5304','url' => 'kotchandpur.jhenaidah.gov.bd'),
  array('id' => '229','district_id' => '29','name' => 'Moheshpur','bn_name' => 'মহেশপুর','code' => '5306','url' => 'moheshpur.jhenaidah.gov.bd'),
  array('id' => '230','district_id' => '30','name' => 'Jhalakathi Sadar','bn_name' => 'ঝালকাঠি সদর','code' => '6101','url' => 'sadar.jhalakathi.gov.bd'),
  array('id' => '231','district_id' => '30','name' => 'Kathalia','bn_name' => 'কাঠালিয়া','code' => '6104','url' => 'kathalia.jhalakathi.gov.bd'),
  array('id' => '232','district_id' => '30','name' => 'Nalchity','bn_name' => 'নলছিটি','code' => '6102','url' => 'nalchity.jhalakathi.gov.bd'),
  array('id' => '233','district_id' => '30','name' => 'Rajapur','bn_name' => 'রাজাপুর','code' => '6103','url' => 'rajapur.jhalakathi.gov.bd'),
  array('id' => '234','district_id' => '31','name' => 'Bauphal','bn_name' => 'বাউফল','code' => '6403','url' => 'bauphal.patuakhali.gov.bd'),
  array('id' => '235','district_id' => '31','name' => 'Patuakhali Sadar','bn_name' => 'পটুয়াখালী সদর','code' => '6401','url' => 'sadar.patuakhali.gov.bd'),
  array('id' => '236','district_id' => '31','name' => 'Dumki','bn_name' => 'দুমকি','code' => '6402','url' => 'dumki.patuakhali.gov.bd'),
  array('id' => '237','district_id' => '31','name' => 'Dashmina','bn_name' => 'দশমিনা','code' => '6405','url' => 'dashmina.patuakhali.gov.bd'),
  array('id' => '238','district_id' => '31','name' => 'Kalapara','bn_name' => 'কলাপাড়া','code' => '6407','url' => 'kalapara.patuakhali.gov.bd'),
  array('id' => '239','district_id' => '31','name' => 'Mirzaganj','bn_name' => 'মির্জাগঞ্জ','code' => '6404','url' => 'mirzaganj.patuakhali.gov.bd'),
  array('id' => '240','district_id' => '31','name' => 'Galachipa','bn_name' => 'গলাচিপা','code' => '6406','url' => 'galachipa.patuakhali.gov.bd'),
  array('id' => '241','district_id' => '31','name' => 'Rangabali','bn_name' => 'মহিপুর','code' => '6408','url' => 'rangabali.patuakhali.gov.bd'),
  array('id' => '242','district_id' => '32','name' => 'Pirojpur Sadar','bn_name' => 'ইন্দুরকানী','code' => '6309','url' => 'sadar.pirojpur.gov.bd'),
  array('id' => '243','district_id' => '32','name' => 'Nazirpur','bn_name' => 'নাজিরপুর','code' => '6302','url' => 'nazirpur.pirojpur.gov.bd'),
  array('id' => '244','district_id' => '32','name' => 'Kawkhali','bn_name' => 'কাউখালী','code' => '6305','url' => 'kawkhali.pirojpur.gov.bd'),
  array('id' => '245','district_id' => '32','name' => 'Zianagar','bn_name' => 'জিয়ানগর','code' => '6307','url' => 'zianagar.pirojpur.gov.bd'),
  array('id' => '246','district_id' => '32','name' => 'Bhandaria','bn_name' => 'ভান্ডারিয়া','code' => '6306','url' => 'bhandaria.pirojpur.gov.bd'),
  array('id' => '247','district_id' => '32','name' => 'Mathbaria','bn_name' => 'মঠবাড়ীয়া','code' => '6308','url' => 'mathbaria.pirojpur.gov.bd'),
  array('id' => '248','district_id' => '32','name' => 'Nesarabad','bn_name' => 'নেছারাবাদ','code' => '6304','url' => 'nesarabad.pirojpur.gov.bd'),
  array('id' => '249','district_id' => '33','name' => 'Barisal Sadar','bn_name' => 'বরিশাল সদর','code' => '5901','url' => 'barisalsadar.barisal.gov.bd'),
  array('id' => '250','district_id' => '33','name' => 'Bakerganj','bn_name' => 'বাকেরগঞ্জ','code' => '5911','url' => 'bakerganj.barisal.gov.bd'),
  array('id' => '251','district_id' => '33','name' => 'Babuganj','bn_name' => 'বাবুগঞ্জ','code' => '5908','url' => 'babuganj.barisal.gov.bd'),
  array('id' => '252','district_id' => '33','name' => 'Wazirpur','bn_name' => 'উজিরপুর','code' => '5906','url' => 'wazirpur.barisal.gov.bd'),
  array('id' => '253','district_id' => '33','name' => 'Banaripara','bn_name' => 'বানারীপাড়া','code' => '5907','url' => 'banaripara.barisal.gov.bd'),
  array('id' => '254','district_id' => '33','name' => 'Gournadi','bn_name' => 'গৌরনদী','code' => '5903','url' => 'gournadi.barisal.gov.bd'),
  array('id' => '255','district_id' => '33','name' => 'Agailjhara','bn_name' => 'আগৈলঝাড়া','code' => '5904','url' => 'agailjhara.barisal.gov.bd'),
  array('id' => '256','district_id' => '33','name' => 'Mehendiganj','bn_name' => 'মেহেন্দিগঞ্জ','code' => '5909','url' => 'mehendiganj.barisal.gov.bd'),
  array('id' => '257','district_id' => '33','name' => 'Muladi','bn_name' => 'মুলাদী','code' => '5902','url' => 'muladi.barisal.gov.bd'),
  array('id' => '258','district_id' => '33','name' => 'Hizla','bn_name' => 'হিজলা','code' => '5905','url' => 'hizla.barisal.gov.bd'),
  array('id' => '259','district_id' => '34','name' => 'Bhola Sadar','bn_name' => 'ভোলা সদর','code' => '6201','url' => 'sadar.bhola.gov.bd'),
  array('id' => '260','district_id' => '34','name' => 'Borhan Sddin','bn_name' => 'বোরহান উদ্দিন','code' => '6203','url' => 'borhanuddin.bhola.gov.bd'),
  array('id' => '261','district_id' => '34','name' => 'Charfesson','bn_name' => 'চরফ্যাশন','code' => '6204','url' => 'charfesson.bhola.gov.bd'),
  array('id' => '262','district_id' => '34','name' => 'Doulatkhan','bn_name' => 'দৌলতখান','code' => '6202','url' => 'doulatkhan.bhola.gov.bd'),
  array('id' => '263','district_id' => '34','name' => 'Monpura','bn_name' => 'মনপুরা','code' => '6208','url' => 'monpura.bhola.gov.bd'),
  array('id' => '264','district_id' => '34','name' => 'Tazumuddin','bn_name' => 'দক্ষিণ আইচা','code' => '6206','url' => 'tazumuddin.bhola.gov.bd'),
  array('id' => '265','district_id' => '34','name' => 'Lalmohan','bn_name' => 'লালমোহন','code' => '6205','url' => 'lalmohan.bhola.gov.bd'),
  array('id' => '266','district_id' => '35','name' => 'Amtali','bn_name' => 'আমতলী','code' => '6004','url' => 'amtali.barguna.gov.bd'),
  array('id' => '267','district_id' => '35','name' => 'Barguna Sadar','bn_name' => 'বরগুনা সদর','code' => '6001','url' => 'sadar.barguna.gov.bd'),
  array('id' => '268','district_id' => '35','name' => 'Betagi','bn_name' => 'বেতাগী','code' => '6002','url' => 'betagi.barguna.gov.bd'),
  array('id' => '269','district_id' => '35','name' => 'Bamna','bn_name' => 'বামনা','code' => '6003','url' => 'bamna.barguna.gov.bd'),
  array('id' => '270','district_id' => '35','name' => 'Pathorghata','bn_name' => 'পাথরঘাটা','code' => '6005','url' => 'pathorghata.barguna.gov.bd'),
  array('id' => '271','district_id' => '35','name' => 'Taltali','bn_name' => 'তালতলি','code' => '6006','url' => 'taltali.barguna.gov.bd'),
  array('id' => '272','district_id' => '36','name' => 'Balaganj','bn_name' => 'বালাগঞ্জ','code' => '2514','url' => 'balaganj.sylhet.gov.bd'),
  array('id' => '273','district_id' => '36','name' => 'Beanibazar','bn_name' => 'বিয়ানীবাজার','code' => '2511','url' => 'beanibazar.sylhet.gov.bd'),
  array('id' => '274','district_id' => '36','name' => 'Bishwanath','bn_name' => 'বিশ্বনাথ','code' => '2509','url' => 'bishwanath.sylhet.gov.bd'),
  array('id' => '275','district_id' => '36','name' => 'Companiganj','bn_name' => 'কোম্পানীগঞ্জ','code' => '2504','url' => 'companiganj.sylhet.gov.bd'),
  array('id' => '276','district_id' => '36','name' => 'Fenchuganj','bn_name' => 'ফেঞ্চুগঞ্জ','code' => '2513','url' => 'fenchuganj.sylhet.gov.bd'),
  array('id' => '277','district_id' => '36','name' => 'Golapganj','bn_name' => 'গোলাপগঞ্জ','code' => '2510','url' => 'golapganj.sylhet.gov.bd'),
  array('id' => '278','district_id' => '36','name' => 'Gowainghat','bn_name' => 'গোয়াইনঘাট','code' => '2506','url' => 'gowainghat.sylhet.gov.bd'),
  array('id' => '279','district_id' => '36','name' => 'Jaintiapur','bn_name' => 'জৈন্তাপুর','code' => '2503','url' => 'jaintiapur.sylhet.gov.bd'),
  array('id' => '280','district_id' => '36','name' => 'Kanaighat','bn_name' => 'কানাইঘাট','code' => '2507','url' => 'kanaighat.sylhet.gov.bd'),
  array('id' => '281','district_id' => '36','name' => 'Sylhet Sadar','bn_name' => 'সিলেট সদর','code' => '2501','url' => 'sylhetsadar.sylhet.gov.bd'),
  array('id' => '282','district_id' => '36','name' => 'Zakiganj','bn_name' => 'জকিগঞ্জ','code' => '2508','url' => 'zakiganj.sylhet.gov.bd'),
  array('id' => '283','district_id' => '36','name' => 'Dakshinsurma','bn_name' => 'দক্ষিণ সুরমা','code' => '2512','url' => 'dakshinsurma.sylhet.gov.bd'),
  array('id' => '284','district_id' => '36','name' => 'Osmaninagar','bn_name' => 'ওসমানীনগর','code' => '2505','url' => 'osmaninagar.sylhet.gov.bd'),
  array('id' => '285','district_id' => '37','name' => 'Barlekha','bn_name' => 'বড়লেখা','code' => '2706','url' => 'barlekha.moulvibazar.gov.bd'),
  array('id' => '286','district_id' => '37','name' => 'Kamolganj','bn_name' => 'কমলগঞ্জ','code' => '2704','url' => 'kamolganj.moulvibazar.gov.bd'),
  array('id' => '287','district_id' => '37','name' => 'Kulaura','bn_name' => 'কুলাউড়া','code' => '2702','url' => 'kulaura.moulvibazar.gov.bd'),
  array('id' => '288','district_id' => '37','name' => 'Moulvibazar Sadar','bn_name' => 'মৌলভীবাজার সদর','code' => '2701','url' => 'moulvibazarsadar.moulvibazar.gov.bd'),
  array('id' => '289','district_id' => '37','name' => 'Rajnagar','bn_name' => 'রাজনগর','code' => '2705','url' => 'rajnagar.moulvibazar.gov.bd'),
  array('id' => '290','district_id' => '37','name' => 'Sreemangal','bn_name' => 'শ্রীমঙ্গল','code' => '2703','url' => 'sreemangal.moulvibazar.gov.bd'),
  array('id' => '291','district_id' => '37','name' => 'Juri','bn_name' => 'জুরী','code' => '2707','url' => 'juri.moulvibazar.gov.bd'),
  array('id' => '292','district_id' => '38','name' => 'Nabiganj','bn_name' => 'নবীগঞ্জ','code' => '2809','url' => 'nabiganj.habiganj.gov.bd'),
  array('id' => '293','district_id' => '38','name' => 'Bahubal','bn_name' => 'বাহুবল','code' => '2805','url' => 'bahubal.habiganj.gov.bd'),
  array('id' => '294','district_id' => '38','name' => 'Ajmiriganj','bn_name' => 'আজমিরীগঞ্জ','code' => '2807','url' => 'ajmiriganj.habiganj.gov.bd'),
  array('id' => '295','district_id' => '38','name' => 'Baniachong','bn_name' => 'বানিয়াচং','code' => '2804','url' => 'baniachong.habiganj.gov.bd'),
  array('id' => '296','district_id' => '38','name' => 'Lakhai','bn_name' => 'লাখাই','code' => '2806','url' => 'lakhai.habiganj.gov.bd'),
  array('id' => '297','district_id' => '38','name' => 'Chunarughat','bn_name' => 'চুনারুঘাট','code' => '2803','url' => 'chunarughat.habiganj.gov.bd'),
  array('id' => '298','district_id' => '38','name' => 'Habiganj Sadar','bn_name' => 'হবিগঞ্জ সদর','code' => '2801','url' => 'habiganjsadar.habiganj.gov.bd'),
  array('id' => '299','district_id' => '38','name' => 'Madhabpur','bn_name' => 'মাধবপুর','code' => '2808','url' => 'madhabpur.habiganj.gov.bd'),
  array('id' => '300','district_id' => '39','name' => 'Sunamganj Sadar','bn_name' => 'সুনামগঞ্জ সদর','code' => '2601','url' => 'sadar.sunamganj.gov.bd'),
  array('id' => '301','district_id' => '39','name' => 'South Sunamganj','bn_name' => 'দক্ষিণ সুনামগঞ্জ','code' => '2608','url' => 'southsunamganj.sunamganj.gov.bd'),
  array('id' => '302','district_id' => '39','name' => 'Bishwambarpur','bn_name' => 'বিশ্বম্ভরপুর','code' => '2602','url' => 'bishwambarpur.sunamganj.gov.bd'),
  array('id' => '303','district_id' => '39','name' => 'Chhatak','bn_name' => 'ছাতক','code' => '2606','url' => 'chhatak.sunamganj.gov.bd'),
  array('id' => '304','district_id' => '39','name' => 'Jagannathpur','bn_name' => 'জগন্নাথপুর','code' => '2610','url' => 'jagannathpur.sunamganj.gov.bd'),
  array('id' => '305','district_id' => '39','name' => 'Dowarabazar','bn_name' => 'দোয়ারাবাজার','code' => '2604','url' => 'dowarabazar.sunamganj.gov.bd'),
  array('id' => '306','district_id' => '39','name' => 'Tahirpur','bn_name' => 'তাহিরপুর','code' => '2603','url' => 'tahirpur.sunamganj.gov.bd'),
  array('id' => '307','district_id' => '39','name' => 'Dharmapasha','bn_name' => 'ধর্মপাশা','code' => '2607','url' => 'dharmapasha.sunamganj.gov.bd'),
  array('id' => '308','district_id' => '39','name' => 'Jamalganj','bn_name' => 'জামালগঞ্জ','code' => '2605','url' => 'jamalganj.sunamganj.gov.bd'),
  array('id' => '309','district_id' => '39','name' => 'Shalla','bn_name' => 'শাল্লা','code' => '2611','url' => 'shalla.sunamganj.gov.bd'),
  array('id' => '310','district_id' => '39','name' => 'Derai','bn_name' => 'দিরাই','code' => '2609','url' => 'derai.sunamganj.gov.bd'),
  array('id' => '311','district_id' => '40','name' => 'Belabo','bn_name' => 'বেলাবো','code' => '2004','url' => 'belabo.narsingdi.gov.bd'),
  array('id' => '312','district_id' => '40','name' => 'Monohardi','bn_name' => 'মনোহরদী','code' => '2002','url' => 'monohardi.narsingdi.gov.bd'),
  array('id' => '313','district_id' => '40','name' => 'Narsingdi Sadar','bn_name' => 'নরসিংদী সদর','code' => '2001','url' => 'narsingdisadar.narsingdi.gov.bd'),
  array('id' => '314','district_id' => '40','name' => 'Palash','bn_name' => 'পলাশ','code' => '2007','url' => 'palash.narsingdi.gov.bd'),
  array('id' => '315','district_id' => '40','name' => 'Raipura','bn_name' => 'রায়পুর','code' => '2006','url' => 'raipura.narsingdi.gov.bd'),
  array('id' => '316','district_id' => '40','name' => 'Shibpur','bn_name' => 'শিবপুর','code' => '2005','url' => 'shibpur.narsingdi.gov.bd'),
  array('id' => '317','district_id' => '41','name' => 'Kaliganj','bn_name' => 'কালীগঞ্জ','code' => '1307','url' => 'kaliganj.gazipur.gov.bd'),
  array('id' => '318','district_id' => '41','name' => 'Kaliakair','bn_name' => 'কালিয়াকৈর','code' => '1306','url' => 'kaliakair.gazipur.gov.bd'),
  array('id' => '319','district_id' => '41','name' => 'Kapasia','bn_name' => 'কাপাসিয়া','code' => '1305','url' => 'kapasia.gazipur.gov.bd'),
  array('id' => '320','district_id' => '41','name' => 'Gazipur Sadar','bn_name' => 'গাজীপুর সদর','code' => '1301','url' => 'sadar.gazipur.gov.bd'),
  array('id' => '321','district_id' => '41','name' => 'Sreepur','bn_name' => 'শ্রীপুর','code' => '1303','url' => 'sreepur.gazipur.gov.bd'),
  array('id' => '322','district_id' => '42','name' => 'Shariatpur Sadar','bn_name' => 'শরিয়তপুর সদর','code' => '2101','url' => 'sadar.shariatpur.gov.bd'),
  array('id' => '323','district_id' => '42','name' => 'Naria','bn_name' => 'নড়িয়া','code' => '2103','url' => 'naria.shariatpur.gov.bd'),
  array('id' => '324','district_id' => '42','name' => 'Zajira','bn_name' => 'জাজিরা','code' => '2102','url' => 'zajira.shariatpur.gov.bd'),
  array('id' => '325','district_id' => '42','name' => 'Gosairhat','bn_name' => 'গোসাইরহাট','code' => '2106','url' => 'gosairhat.shariatpur.gov.bd'),
  array('id' => '326','district_id' => '42','name' => 'Bhedarganj','bn_name' => 'ভেদরগঞ্জ','code' => '2104','url' => 'bhedarganj.shariatpur.gov.bd'),
  array('id' => '327','district_id' => '42','name' => 'Damudya','bn_name' => 'ডামুড্যা','code' => '2105','url' => 'damudya.shariatpur.gov.bd'),
  array('id' => '328','district_id' => '43','name' => 'Araihazar','bn_name' => 'আড়াইহাজার','code' => '1507','url' => 'araihazar.narayanganj.gov.bd'),
  array('id' => '329','district_id' => '8','name' => 'Bandar','bn_name' => 'বন্দর','code' => '0127','url' => 'bandar.narayanganj.gov.bd'),
  array('id' => '330','district_id' => '43','name' => 'Narayanganj Sadar','bn_name' => 'নারায়নগঞ্জ সদর','code' => '1501','url' => 'narayanganjsadar.narayanganj.gov.bd'),
  array('id' => '331','district_id' => '43','name' => 'Rupganj','bn_name' => 'রূপগঞ্জ','code' => '1503','url' => 'rupganj.narayanganj.gov.bd'),
  array('id' => '332','district_id' => '43','name' => 'Sonargaon','bn_name' => 'সোনারগাঁও','code' => '1505','url' => 'sonargaon.narayanganj.gov.bd'),
  array('id' => '333','district_id' => '44','name' => 'Basail','bn_name' => 'বাসাইল','code' => '2409','url' => 'basail.tangail.gov.bd'),
  array('id' => '334','district_id' => '44','name' => 'Bhuapur','bn_name' => 'ভুয়াপুর','code' => '2405','url' => 'bhuapur.tangail.gov.bd'),
  array('id' => '335','district_id' => '44','name' => 'Delduar','bn_name' => 'দেলদুয়ার','code' => '2410','url' => 'delduar.tangail.gov.bd'),
  array('id' => '336','district_id' => '44','name' => 'Ghatail','bn_name' => 'ঘাটাইল','code' => '2406','url' => 'ghatail.tangail.gov.bd'),
  array('id' => '337','district_id' => '44','name' => 'Gopalpur','bn_name' => 'গোপালপুর','code' => '2404','url' => 'gopalpur.tangail.gov.bd'),
  array('id' => '338','district_id' => '44','name' => 'Madhupur','bn_name' => 'মধুপুর','code' => '2402','url' => 'madhupur.tangail.gov.bd'),
  array('id' => '339','district_id' => '44','name' => 'Mirzapur','bn_name' => 'মির্জাপুর','code' => '2411','url' => 'mirzapur.tangail.gov.bd'),
  array('id' => '340','district_id' => '44','name' => 'Nagarpur','bn_name' => 'নাগরপুর','code' => '2412','url' => 'nagarpur.tangail.gov.bd'),
  array('id' => '341','district_id' => '44','name' => 'Sakhipur','bn_name' => 'সখিপুর','code' => '2408','url' => 'sakhipur.tangail.gov.bd'),
  array('id' => '342','district_id' => '44','name' => 'Tangail Sadar','bn_name' => 'টাঙ্গাইল সদর','code' => '2401','url' => 'tangailsadar.tangail.gov.bd'),
  array('id' => '343','district_id' => '44','name' => 'Kalihati','bn_name' => 'কালিহাতী','code' => '2407','url' => 'kalihati.tangail.gov.bd'),
  array('id' => '344','district_id' => '44','name' => 'Dhanbari','bn_name' => 'ধনবাড়ী','code' => '2403','url' => 'dhanbari.tangail.gov.bd'),
  array('id' => '345','district_id' => '45','name' => 'Itna','bn_name' => 'ইটনা','code' => '2307','url' => 'itna.kishoreganj.gov.bd'),
  array('id' => '346','district_id' => '45','name' => 'Katiadi','bn_name' => 'কটিয়াদী','code' => '2304','url' => 'katiadi.kishoreganj.gov.bd'),
  array('id' => '347','district_id' => '45','name' => 'Bhairab','bn_name' => 'ভৈরব','code' => '2313','url' => 'bhairab.kishoreganj.gov.bd'),
  array('id' => '348','district_id' => '45','name' => 'Tarail','bn_name' => 'তাড়াইল','code' => '2305','url' => 'tarail.kishoreganj.gov.bd'),
  array('id' => '349','district_id' => '45','name' => 'Hossainpur','bn_name' => 'হোসেনপুর','code' => '2303','url' => 'hossainpur.kishoreganj.gov.bd'),
  array('id' => '350','district_id' => '45','name' => 'Pakundia','bn_name' => 'পাকুন্দিয়া','code' => '2302','url' => 'pakundia.kishoreganj.gov.bd'),
  array('id' => '351','district_id' => '45','name' => 'Kuliarchar','bn_name' => 'কুলিয়ারচর','code' => '2312','url' => 'kuliarchar.kishoreganj.gov.bd'),
  array('id' => '352','district_id' => '45','name' => 'Kishoreganj Sadar','bn_name' => 'কিশোরগঞ্জ সদর','code' => '2301','url' => 'kishoreganjsadar.kishoreganj.gov.bd'),
  array('id' => '353','district_id' => '45','name' => 'Karimgonj','bn_name' => 'করিমগঞ্জ','code' => '2308','url' => 'karimgonj.kishoreganj.gov.bd'),
  array('id' => '354','district_id' => '45','name' => 'Bajitpur','bn_name' => 'বাজিতপুর','code' => '2306','url' => 'bajitpur.kishoreganj.gov.bd'),
  array('id' => '355','district_id' => '45','name' => 'Austagram','bn_name' => 'অষ্টগ্রাম','code' => '2311','url' => 'austagram.kishoreganj.gov.bd'),
  array('id' => '356','district_id' => '45','name' => 'Mithamoin','bn_name' => 'মিঠামইন','code' => '2309','url' => 'mithamoin.kishoreganj.gov.bd'),
  array('id' => '357','district_id' => '45','name' => 'Nikli','bn_name' => 'নিকলী','code' => '2310','url' => 'nikli.kishoreganj.gov.bd'),
  array('id' => '358','district_id' => '46','name' => 'Harirampur','bn_name' => 'হরিরামপুর','code' => '1406','url' => 'harirampur.manikganj.gov.bd'),
  array('id' => '359','district_id' => '46','name' => 'Saturia','bn_name' => 'সাটুরিয়া','code' => '1403','url' => 'saturia.manikganj.gov.bd'),
  array('id' => '360','district_id' => '46','name' => 'Manikganj Sadar','bn_name' => 'মানিকগঞ্জ সদর','code' => '1401','url' => 'sadar.manikganj.gov.bd'),
  array('id' => '361','district_id' => '46','name' => 'Gior','bn_name' => 'ঘিওর','code' => '1407','url' => 'gior.manikganj.gov.bd'),
  array('id' => '362','district_id' => '46','name' => 'Shibaloy','bn_name' => 'শিবালয়','code' => '1405','url' => 'shibaloy.manikganj.gov.bd'),
  array('id' => '363','district_id' => '46','name' => 'Doulatpur','bn_name' => 'দৌলতপুর','code' => '1402','url' => 'doulatpur.manikganj.gov.bd'),
  array('id' => '364','district_id' => '46','name' => 'Singiar','bn_name' => 'সিংগাইর','code' => '1404','url' => 'singiar.manikganj.gov.bd'),
  array('id' => '365','district_id' => '47','name' => 'Savar','bn_name' => 'সাভার','code' => '1246','url' => 'savar.dhaka.gov.bd'),
  array('id' => '366','district_id' => '47','name' => 'Dhamrai','bn_name' => 'ধামরাই','code' => '1242','url' => 'dhamrai.dhaka.gov.bd'),
  array('id' => '367','district_id' => '47','name' => 'Keraniganj','bn_name' => 'কেরাণীগঞ্জ','code' => '1244','url' => 'keraniganj.dhaka.gov.bd'),
  array('id' => '368','district_id' => '47','name' => 'Nawabganj','bn_name' => 'নবাবগঞ্জ','code' => '1245','url' => 'nawabganj.dhaka.gov.bd'),
  array('id' => '369','district_id' => '47','name' => 'Dohar','bn_name' => 'দোহার','code' => '1243','url' => 'dohar.dhaka.gov.bd'),
  array('id' => '370','district_id' => '48','name' => 'Munshiganj Sadar','bn_name' => 'মুন্সিগঞ্জ সদর','code' => '1601','url' => 'sadar.munshiganj.gov.bd'),
  array('id' => '371','district_id' => '48','name' => 'Sreenagar','bn_name' => 'শ্রীনগর','code' => '1603','url' => 'sreenagar.munshiganj.gov.bd'),
  array('id' => '372','district_id' => '48','name' => 'Sirajdikhan','bn_name' => 'সিরাজদিখান','code' => '1606','url' => 'sirajdikhan.munshiganj.gov.bd'),
  array('id' => '373','district_id' => '48','name' => 'Louhajanj','bn_name' => 'লৌহজং','code' => '1605','url' => 'louhajanj.munshiganj.gov.bd'),
  array('id' => '374','district_id' => '48','name' => 'Gajaria','bn_name' => 'গজারিয়া','code' => '1602','url' => 'gajaria.munshiganj.gov.bd'),
  array('id' => '375','district_id' => '48','name' => 'Tongibari','bn_name' => 'টংগীবাড়ি','code' => '1604','url' => 'tongibari.munshiganj.gov.bd'),
  array('id' => '376','district_id' => '49','name' => 'Rajbari Sadar','bn_name' => 'রাজবাড়ী সদর','code' => '2201','url' => 'sadar.rajbari.gov.bd'),
  array('id' => '377','district_id' => '49','name' => 'Goalanda','bn_name' => 'গোয়ালন্দ','code' => '2204','url' => 'goalanda.rajbari.gov.bd'),
  array('id' => '378','district_id' => '49','name' => 'Pangsa','bn_name' => 'পাংশা','code' => '2202','url' => 'pangsa.rajbari.gov.bd'),
  array('id' => '379','district_id' => '49','name' => 'Baliakandi','bn_name' => 'বালিয়াকান্দি','code' => '2203','url' => 'baliakandi.rajbari.gov.bd'),
  array('id' => '380','district_id' => '49','name' => 'Kalukhali','bn_name' => 'কালুখালী','code' => '2205','url' => 'kalukhali.rajbari.gov.bd'),
  array('id' => '381','district_id' => '50','name' => 'Madaripur Sadar','bn_name' => 'মাদারীপুর সদর','code' => '1901','url' => 'sadar.madaripur.gov.bd'),
  array('id' => '382','district_id' => '50','name' => 'Shibchar','bn_name' => 'শিবচর','code' => '1902','url' => 'shibchar.madaripur.gov.bd'),
  array('id' => '383','district_id' => '50','name' => 'Kalkini','bn_name' => 'কালকিনি','code' => '1904','url' => 'kalkini.madaripur.gov.bd'),
  array('id' => '384','district_id' => '50','name' => 'Rajoir','bn_name' => 'রাজৈর','code' => '1903','url' => 'rajoir.madaripur.gov.bd'),
  array('id' => '385','district_id' => '51','name' => 'Gopalganj Sadar','bn_name' => 'গোপালগঞ্জ সদর','code' => '1701','url' => 'sadar.gopalganj.gov.bd'),
  array('id' => '386','district_id' => '51','name' => 'Kashiani','bn_name' => 'কাশিয়ানী','code' => '1703','url' => 'kashiani.gopalganj.gov.bd'),
  array('id' => '387','district_id' => '51','name' => 'Tungipara','bn_name' => 'টুংগীপাড়া','code' => '1705','url' => 'tungipara.gopalganj.gov.bd'),
  array('id' => '388','district_id' => '51','name' => 'Kotalipara','bn_name' => 'কোটালীপাড়া','code' => '1704','url' => 'kotalipara.gopalganj.gov.bd'),
  array('id' => '389','district_id' => '51','name' => 'Muksudpur','bn_name' => 'মুকসুদপুর','code' => '1702','url' => 'muksudpur.gopalganj.gov.bd'),
  array('id' => '390','district_id' => '52','name' => 'Faridpur Sadar','bn_name' => 'ফরিদপুর সদর','code' => '1801','url' => 'sadar.faridpur.gov.bd'),
  array('id' => '391','district_id' => '52','name' => 'Alfadanga','bn_name' => 'আলফাডাঙ্গা','code' => '1803','url' => 'alfadanga.faridpur.gov.bd'),
  array('id' => '392','district_id' => '52','name' => 'Boalmari','bn_name' => 'বোয়ালমারী','code' => '1807','url' => 'boalmari.faridpur.gov.bd'),
  array('id' => '393','district_id' => '52','name' => 'Sadarpur','bn_name' => 'সদরপুর','code' => '1804','url' => 'sadarpur.faridpur.gov.bd'),
  array('id' => '394','district_id' => '52','name' => 'Nagarkanda','bn_name' => 'নগরকান্দা','code' => '1805','url' => 'nagarkanda.faridpur.gov.bd'),
  array('id' => '395','district_id' => '52','name' => 'Bhanga','bn_name' => 'ভাঙ্গা','code' => '1806','url' => 'bhanga.faridpur.gov.bd'),
  array('id' => '396','district_id' => '52','name' => 'Charbhadrasan','bn_name' => 'চরভদ্রাসন','code' => '1802','url' => 'charbhadrasan.faridpur.gov.bd'),
  array('id' => '397','district_id' => '52','name' => 'Madhukhali','bn_name' => 'মধুখালী','code' => '1808','url' => 'madhukhali.faridpur.gov.bd'),
  array('id' => '398','district_id' => '52','name' => 'Saltha','bn_name' => 'সালথা','code' => '1809','url' => 'saltha.faridpur.gov.bd'),
  array('id' => '399','district_id' => '53','name' => 'Panchagarh Sadar','bn_name' => 'পঞ্চগড় সদর','code' => '4501','url' => 'panchagarhsadar.panchagarh.gov.bd'),
  array('id' => '400','district_id' => '53','name' => 'Debiganj','bn_name' => 'দেবীগঞ্জ','code' => '4505','url' => 'debiganj.panchagarh.gov.bd'),
  array('id' => '401','district_id' => '53','name' => 'Boda','bn_name' => 'বোদা','code' => '4504','url' => 'boda.panchagarh.gov.bd'),
  array('id' => '402','district_id' => '53','name' => 'Atwari','bn_name' => 'আটোয়ারী','code' => '4503','url' => 'atwari.panchagarh.gov.bd'),
  array('id' => '403','district_id' => '53','name' => 'Tetulia','bn_name' => 'তেতুলিয়া','code' => '4502','url' => 'tetulia.panchagarh.gov.bd'),
  array('id' => '404','district_id' => '54','name' => 'Nawabganj','bn_name' => 'নবাবগঞ্জ','code' => '4310','url' => 'nawabganj.dinajpur.gov.bd'),
  array('id' => '405','district_id' => '54','name' => 'Birganj','bn_name' => 'বীরগঞ্জ','code' => '4302','url' => 'birganj.dinajpur.gov.bd'),
  array('id' => '406','district_id' => '54','name' => 'Ghoraghat','bn_name' => 'ঘোড়াঘাট','code' => '4313','url' => 'ghoraghat.dinajpur.gov.bd'),
  array('id' => '407','district_id' => '54','name' => 'Birampur','bn_name' => 'বিরামপুর','code' => '4311','url' => 'birampur.dinajpur.gov.bd'),
  array('id' => '408','district_id' => '54','name' => 'Parbatipur','bn_name' => 'পার্বতীপুর','code' => '4308','url' => 'parbatipur.dinajpur.gov.bd'),
  array('id' => '409','district_id' => '54','name' => 'Bochaganj','bn_name' => 'বোচাগঞ্জ','code' => '4305','url' => 'bochaganj.dinajpur.gov.bd'),
  array('id' => '410','district_id' => '54','name' => 'Kaharol','bn_name' => 'কাহারোল','code' => '4304','url' => 'kaharol.dinajpur.gov.bd'),
  array('id' => '411','district_id' => '54','name' => 'Fulbari','bn_name' => 'ফুলবাড়ী','code' => '4309','url' => 'fulbari.dinajpur.gov.bd'),
  array('id' => '412','district_id' => '54','name' => 'Dinajpur Sadar','bn_name' => 'দিনাজপুর সদর','code' => '4301','url' => 'dinajpursadar.dinajpur.gov.bd'),
  array('id' => '413','district_id' => '54','name' => 'Hakimpur','bn_name' => 'হাকিমপুর','code' => '4312','url' => 'hakimpur.dinajpur.gov.bd'),
  array('id' => '414','district_id' => '54','name' => 'Khansama','bn_name' => 'খানসামা','code' => '4303','url' => 'khansama.dinajpur.gov.bd'),
  array('id' => '415','district_id' => '54','name' => 'Birol','bn_name' => 'বিরল','code' => '4307','url' => 'birol.dinajpur.gov.bd'),
  array('id' => '416','district_id' => '54','name' => 'Chirirbandar','bn_name' => 'চিরিরবন্দর','code' => '4306','url' => 'chirirbandar.dinajpur.gov.bd'),
  array('id' => '417','district_id' => '55','name' => 'Lalmonirhat Sadar','bn_name' => 'লালমনিরহাট সদর','code' => '4601','url' => 'sadar.lalmonirhat.gov.bd'),
  array('id' => '418','district_id' => '55','name' => 'Kaliganj','bn_name' => 'কালীগঞ্জ','code' => '4604','url' => 'kaliganj.lalmonirhat.gov.bd'),
  array('id' => '419','district_id' => '55','name' => 'Hatibandha','bn_name' => 'হাতীবান্ধা','code' => '4603','url' => 'hatibandha.lalmonirhat.gov.bd'),
  array('id' => '420','district_id' => '55','name' => 'Patgram','bn_name' => 'পাটগ্রাম','code' => '4602','url' => 'patgram.lalmonirhat.gov.bd'),
  array('id' => '421','district_id' => '55','name' => 'Aditmari','bn_name' => 'আদিতমারী','code' => '4605','url' => 'aditmari.lalmonirhat.gov.bd'),
  array('id' => '422','district_id' => '56','name' => 'Syedpur','bn_name' => 'সৈয়দপুর','code' => '4204','url' => 'syedpur.nilphamari.gov.bd'),
  array('id' => '423','district_id' => '56','name' => 'Domar','bn_name' => 'ডোমার','code' => '4205','url' => 'domar.nilphamari.gov.bd'),
  array('id' => '424','district_id' => '56','name' => 'Dimla','bn_name' => 'ডিমলা','code' => '4202','url' => 'dimla.nilphamari.gov.bd'),
  array('id' => '425','district_id' => '56','name' => 'Jaldhaka','bn_name' => 'জলঢাকা','code' => '4206','url' => 'jaldhaka.nilphamari.gov.bd'),
  array('id' => '426','district_id' => '56','name' => 'Kishorganj','bn_name' => 'কিশোরগঞ্জ','code' => '4203','url' => 'kishorganj.nilphamari.gov.bd'),
  array('id' => '427','district_id' => '56','name' => 'Nilphamari Sadar','bn_name' => 'নীলফামারী সদর','code' => '4201','url' => 'nilphamarisadar.nilphamari.gov.bd'),
  array('id' => '428','district_id' => '57','name' => 'Sadullapur','bn_name' => 'সাদুল্লাপুর','code' => '4703','url' => 'sadullapur.gaibandha.gov.bd'),
  array('id' => '429','district_id' => '57','name' => 'Gaibandha Sadar','bn_name' => 'গাইবান্ধা সদর','code' => '4701','url' => 'gaibandhasadar.gaibandha.gov.bd'),
  array('id' => '430','district_id' => '57','name' => 'Palashbari','bn_name' => 'পলাশবাড়ী','code' => '4704','url' => 'palashbari.gaibandha.gov.bd'),
  array('id' => '431','district_id' => '57','name' => 'Saghata','bn_name' => 'সাঘাটা','code' => '4707','url' => 'saghata.gaibandha.gov.bd'),
  array('id' => '432','district_id' => '57','name' => 'Gobindaganj','bn_name' => 'গোবিন্দগঞ্জ','code' => '4706','url' => 'gobindaganj.gaibandha.gov.bd'),
  array('id' => '433','district_id' => '57','name' => 'Sundarganj','bn_name' => 'সুন্দরগঞ্জ','code' => '4702','url' => 'sundarganj.gaibandha.gov.bd'),
  array('id' => '434','district_id' => '57','name' => 'Phulchari','bn_name' => 'ফুলছড়ি','code' => '4705','url' => 'phulchari.gaibandha.gov.bd'),
  array('id' => '435','district_id' => '58','name' => 'Thakurgaon Sadar','bn_name' => 'ঠাকুরগাঁও সদর','code' => '4401','url' => 'thakurgaonsadar.thakurgaon.gov.bd'),
  array('id' => '436','district_id' => '58','name' => 'Pirganj','bn_name' => 'পীরগঞ্জ','code' => '4404','url' => 'pirganj.thakurgaon.gov.bd'),
  array('id' => '437','district_id' => '58','name' => 'Ranisankail','bn_name' => 'রাণীশংকৈল','code' => '4402','url' => 'ranisankail.thakurgaon.gov.bd'),
  array('id' => '438','district_id' => '58','name' => 'Haripur','bn_name' => 'হরিপুর','code' => '4405','url' => 'haripur.thakurgaon.gov.bd'),
  array('id' => '439','district_id' => '58','name' => 'Baliadangi','bn_name' => 'বালিয়াডাঙ্গী','code' => '4403','url' => 'baliadangi.thakurgaon.gov.bd'),
  array('id' => '440','district_id' => '59','name' => 'Rangpur Sadar','bn_name' => 'রংপুর সদর','code' => '4101','url' => 'rangpursadar.rangpur.gov.bd'),
  array('id' => '441','district_id' => '59','name' => 'Gangachara','bn_name' => 'গঙ্গাছড়া','code' => '4102','url' => 'gangachara.rangpur.gov.bd'),
  array('id' => '442','district_id' => '59','name' => 'Taragonj','bn_name' => 'তারাগঞ্জ','code' => '4104','url' => 'taragonj.rangpur.gov.bd'),
  array('id' => '443','district_id' => '59','name' => 'Badargonj','bn_name' => 'বদরগঞ্জ','code' => '4105','url' => 'badargonj.rangpur.gov.bd'),
  array('id' => '444','district_id' => '59','name' => 'Mithapukur','bn_name' => 'মিঠাপুকুর','code' => '4107','url' => 'mithapukur.rangpur.gov.bd'),
  array('id' => '445','district_id' => '59','name' => 'Pirgonj','bn_name' => 'পীরগঞ্জ','code' => '4108','url' => 'pirgonj.rangpur.gov.bd'),
  array('id' => '446','district_id' => '59','name' => 'Kaunia','bn_name' => 'কাউনিয়া','code' => '4103','url' => 'kaunia.rangpur.gov.bd'),
  array('id' => '447','district_id' => '59','name' => 'Pirgacha','bn_name' => 'পীরগাছা','code' => '4106','url' => 'pirgacha.rangpur.gov.bd'),
  array('id' => '448','district_id' => '60','name' => 'Kurigram Sadar','bn_name' => 'কুড়িগ্রাম সদর','code' => '4801','url' => 'kurigramsadar.kurigram.gov.bd'),
  array('id' => '449','district_id' => '60','name' => 'Nageshwari','bn_name' => 'নাগেশ্বরী','code' => '4803','url' => 'nageshwari.kurigram.gov.bd'),
  array('id' => '450','district_id' => '60','name' => 'Bhurungamari','bn_name' => 'ভুরুঙ্গামারী','code' => '4802','url' => 'bhurungamari.kurigram.gov.bd'),
  array('id' => '451','district_id' => '60','name' => 'Phulbari','bn_name' => 'ফুলবাড়ী','code' => '4804','url' => 'phulbari.kurigram.gov.bd'),
  array('id' => '452','district_id' => '60','name' => 'Rajarhat','bn_name' => 'রাজারহাট','code' => '4805','url' => 'rajarhat.kurigram.gov.bd'),
  array('id' => '453','district_id' => '60','name' => 'Ulipur','bn_name' => 'উলিপুর','code' => '4806','url' => 'ulipur.kurigram.gov.bd'),
  array('id' => '454','district_id' => '60','name' => 'Chilmari','bn_name' => 'চিলমারী','code' => '4808','url' => 'chilmari.kurigram.gov.bd'),
  array('id' => '455','district_id' => '60','name' => 'Rowmari','bn_name' => 'রৌমারী','code' => '4807','url' => 'rowmari.kurigram.gov.bd'),
  array('id' => '456','district_id' => '60','name' => 'Charrajibpur','bn_name' => 'চর রাজিবপুর','code' => '4809','url' => 'charrajibpur.kurigram.gov.bd'),
  array('id' => '457','district_id' => '61','name' => 'Sherpur Sadar','bn_name' => 'শেরপুর সদর','code' => '3101','url' => 'sherpursadar.sherpur.gov.bd'),
  array('id' => '458','district_id' => '61','name' => 'Nalitabari','bn_name' => 'নালিতাবাড়ী','code' => '3104','url' => 'nalitabari.sherpur.gov.bd'),
  array('id' => '459','district_id' => '61','name' => 'Sreebordi','bn_name' => 'শ্রীবরদী','code' => '3102','url' => 'sreebordi.sherpur.gov.bd'),
  array('id' => '460','district_id' => '61','name' => 'Nokla','bn_name' => 'নকলা','code' => '3105','url' => 'nokla.sherpur.gov.bd'),
  array('id' => '461','district_id' => '61','name' => 'Jhenaigati','bn_name' => 'ঝিনাইগাতী','code' => '3103','url' => 'jhenaigati.sherpur.gov.bd'),
  array('id' => '462','district_id' => '62','name' => 'Fulbaria','bn_name' => 'ফুলবাড়ীয়া','code' => '2912','url' => 'fulbaria.mymensingh.gov.bd'),
  array('id' => '463','district_id' => '62','name' => 'Trishal','bn_name' => 'ত্রিশাল','code' => '2909','url' => 'trishal.mymensingh.gov.bd'),
  array('id' => '464','district_id' => '62','name' => 'Bhaluka','bn_name' => 'ভালুকা','code' => '2911','url' => 'bhaluka.mymensingh.gov.bd'),
  array('id' => '465','district_id' => '62','name' => 'Muktagacha','bn_name' => 'মুক্তাগাছা','code' => '2906','url' => 'muktagacha.mymensingh.gov.bd'),
  array('id' => '466','district_id' => '62','name' => 'Mymensingh Sadar','bn_name' => 'ময়মনসিংহ সদর','code' => '2901','url' => 'mymensinghsadar.mymensingh.gov.bd'),
  array('id' => '467','district_id' => '62','name' => 'Dhobaura','bn_name' => 'ধোবাউড়া','code' => '2904','url' => 'dhobaura.mymensingh.gov.bd'),
  array('id' => '468','district_id' => '62','name' => 'Phulpur','bn_name' => 'ফুলপুর','code' => '2905','url' => 'phulpur.mymensingh.gov.bd'),
  array('id' => '469','district_id' => '62','name' => 'Haluaghat','bn_name' => 'হালুয়াঘাট','code' => '2903','url' => 'haluaghat.mymensingh.gov.bd'),
  array('id' => '470','district_id' => '62','name' => 'Gouripur','bn_name' => 'গৌরীপুর','code' => '2907','url' => 'gouripur.mymensingh.gov.bd'),
  array('id' => '471','district_id' => '62','name' => 'Gafargaon','bn_name' => 'গফরগাঁও','code' => '2910','url' => 'gafargaon.mymensingh.gov.bd'),
  array('id' => '472','district_id' => '62','name' => 'Iswarganj','bn_name' => 'ঈশ্বরগঞ্জ','code' => '2902','url' => 'iswarganj.mymensingh.gov.bd'),
  array('id' => '473','district_id' => '62','name' => 'Nandail','bn_name' => 'নান্দাইল','code' => '2908','url' => 'nandail.mymensingh.gov.bd'),
  array('id' => '474','district_id' => '62','name' => 'Tarakanda','bn_name' => 'তারাকান্দা','code' => '2913','url' => 'tarakanda.mymensingh.gov.bd'),
  array('id' => '475','district_id' => '63','name' => 'Jamalpur Sadar','bn_name' => 'জামালপুর সদর','code' => '3201','url' => 'jamalpursadar.jamalpur.gov.bd'),
  array('id' => '476','district_id' => '63','name' => 'Melandah','bn_name' => 'মেলান্দহ','code' => '3203','url' => 'melandah.jamalpur.gov.bd'),
  array('id' => '477','district_id' => '63','name' => 'Islampur','bn_name' => 'ইসলামপুর','code' => '3202','url' => 'islampur.jamalpur.gov.bd'),
  array('id' => '478','district_id' => '63','name' => 'Dewangonj','bn_name' => 'দেওয়ানগঞ্জ','code' => '3204','url' => 'dewangonj.jamalpur.gov.bd'),
  array('id' => '479','district_id' => '63','name' => 'Sarishabari','bn_name' => 'সরিষাবাড়ী','code' => '3206','url' => 'sarishabari.jamalpur.gov.bd'),
  array('id' => '480','district_id' => '63','name' => 'Madarganj','bn_name' => 'মাদারগঞ্জ','code' => '3205','url' => 'madarganj.jamalpur.gov.bd'),
  array('id' => '481','district_id' => '63','name' => 'Bokshiganj','bn_name' => 'বকশীগঞ্জ','code' => '3207','url' => 'bokshiganj.jamalpur.gov.bd'),
  array('id' => '482','district_id' => '64','name' => 'Barhatta','bn_name' => 'বারহাট্টা','code' => '3005','url' => 'barhatta.netrokona.gov.bd'),
  array('id' => '483','district_id' => '64','name' => 'Durgapur','bn_name' => 'দুর্গাপুর','code' => '3002','url' => 'durgapur.netrokona.gov.bd'),
  array('id' => '484','district_id' => '64','name' => 'Kendua','bn_name' => 'কেন্দুয়া','code' => '3009','url' => 'kendua.netrokona.gov.bd'),
  array('id' => '485','district_id' => '64','name' => 'Atpara','bn_name' => 'আটপাড়া','code' => '3007','url' => 'atpara.netrokona.gov.bd'),
  array('id' => '486','district_id' => '64','name' => 'Madan','bn_name' => 'মদন','code' => '3010','url' => 'madan.netrokona.gov.bd'),
  array('id' => '487','district_id' => '64','name' => 'Khaliajuri','bn_name' => 'খালিয়াজুরী','code' => '3008','url' => 'khaliajuri.netrokona.gov.bd'),
  array('id' => '488','district_id' => '64','name' => 'Kalmakanda','bn_name' => 'কলমাকান্দা','code' => '3003','url' => 'kalmakanda.netrokona.gov.bd'),
  array('id' => '489','district_id' => '64','name' => 'Mohongonj','bn_name' => 'মোহনগঞ্জ','code' => '3006','url' => 'mohongonj.netrokona.gov.bd'),
  array('id' => '490','district_id' => '64','name' => 'Purbadhala','bn_name' => 'পূর্বধলা','code' => '3004','url' => 'purbadhala.netrokona.gov.bd'),
  array('id' => '491','district_id' => '64','name' => 'Netrokona Sadar','bn_name' => 'নেত্রকোণা সদর','code' => '3001','url' => 'netrokonasadar.netrokona.gov.bd'),
  array('id' => '492','district_id' => '7','name' => NULL,'bn_name' => 'চন্দ্রগঞ্জ','code' => '0706','url' => NULL),
  array('id' => '493','district_id' => '47','name' => NULL,'bn_name' => 'কোতোয়ালী','code' => '1201','url' => NULL),
  array('id' => '494','district_id' => '47','name' => NULL,'bn_name' => 'আশুলিয়া','code' => '1247','url' => NULL),
  array('id' => '495','district_id' => '47','name' => NULL,'bn_name' => 'গুলশান','code' => '1231','url' => NULL),
  array('id' => '496','district_id' => '47','name' => NULL,'bn_name' => 'মিরপুর','code' => '1214','url' => NULL),
  array('id' => '497','district_id' => '47','name' => NULL,'bn_name' => 'ডেমরা','code' => '1228','url' => NULL),
  array('id' => '498','district_id' => '47','name' => NULL,'bn_name' => 'ভাটারা','code' => '1211','url' => NULL),
  array('id' => '499','district_id' => '47','name' => NULL,'bn_name' => 'মতিঝিল','code' => '1215','url' => NULL),
  array('id' => '500','district_id' => '47','name' => NULL,'bn_name' => 'মুগদা','code' => '1248','url' => NULL),
  array('id' => '501','district_id' => '47','name' => NULL,'bn_name' => 'বংশাল','code' => '1218','url' => NULL),
  array('id' => '502','district_id' => '47','name' => NULL,'bn_name' => 'দারুস সালাম','code' => '1223','url' => NULL),
  array('id' => '503','district_id' => '47','name' => NULL,'bn_name' => 'খিলক্ষেত','code' => '1233','url' => NULL),
  array('id' => '504','district_id' => '47','name' => NULL,'bn_name' => 'কামরাঙ্গীরচর','code' => '1235','url' => NULL),
  array('id' => '505','district_id' => '47','name' => NULL,'bn_name' => 'যাত্রাবাড়ী','code' => '1212','url' => NULL),
  array('id' => '506','district_id' => '47','name' => NULL,'bn_name' => 'ক্যান্টনমেন্ট','code' => '1234','url' => NULL),
  array('id' => '507','district_id' => '47','name' => NULL,'bn_name' => 'কাফরুল','code' => '1236','url' => NULL),
  array('id' => '508','district_id' => '47','name' => NULL,'bn_name' => 'শাহজানপুর','code' => '1221','url' => NULL),
  array('id' => '509','district_id' => '47','name' => NULL,'bn_name' => 'তুরাগ','code' => '1227','url' => NULL),
  array('id' => '510','district_id' => '47','name' => NULL,'bn_name' => 'কদমতলী','code' => '1238','url' => NULL),
  array('id' => '511','district_id' => '47','name' => NULL,'bn_name' => 'পল্লবী','code' => '1219','url' => NULL),
  array('id' => '512','district_id' => '47','name' => NULL,'bn_name' => 'ভাষানটেক','code' => '1225','url' => NULL),
  array('id' => '513','district_id' => '47','name' => NULL,'bn_name' => 'শাহআলী','code' => '1226','url' => NULL),
  array('id' => '514','district_id' => '47','name' => NULL,'bn_name' => 'আদাবর','code' => '1241','url' => NULL),
  array('id' => '515','district_id' => '47','name' => NULL,'bn_name' => 'উত্তরখান','code' => '1240','url' => NULL),
  array('id' => '516','district_id' => '41','name' => NULL,'bn_name' => 'টঙ্গী','code' => '1302','url' => NULL),
  array('id' => '517','district_id' => '41','name' => NULL,'bn_name' => 'জয়দেবপুর','code' => '1304','url' => NULL),
  array('id' => '518','district_id' => '41','name' => NULL,'bn_name' => 'কাশিমপুর','code' => '1308','url' => NULL),
  array('id' => '519','district_id' => '41','name' => NULL,'bn_name' => 'কোনাবাড়ী','code' => '1309','url' => NULL),
  array('id' => '520','district_id' => '41','name' => NULL,'bn_name' => 'গাছা','code' => '1310','url' => NULL),
  array('id' => '521','district_id' => '41','name' => NULL,'bn_name' => 'বাসন','code' => '1311','url' => NULL),
  array('id' => '522','district_id' => '43','name' => NULL,'bn_name' => 'ফতুল্লা','code' => '1502','url' => NULL),
  array('id' => '523','district_id' => '43','name' => NULL,'bn_name' => 'সিদ্ধিরগঞ্জ','code' => '1504','url' => NULL),
  array('id' => '524','district_id' => '43','name' => NULL,'bn_name' => 'কাঁচপুর','code' => '1506','url' => NULL),
  array('id' => '525','district_id' => '50','name' => NULL,'bn_name' => 'ডাসার','code' => '1905','url' => NULL),
  array('id' => '526','district_id' => '40','name' => NULL,'bn_name' => 'মাধবদী','code' => '2003','url' => NULL),
  array('id' => '527','district_id' => '42','name' => NULL,'bn_name' => 'পালং','code' => '2107','url' => NULL),
  array('id' => '528','district_id' => '15','name' => NULL,'bn_name' => 'রাজশাহী','code' => '3301','url' => NULL),
  array('id' => '529','district_id' => '15','name' => NULL,'bn_name' => 'রাজপাড়া','code' => '3311','url' => NULL),
  array('id' => '530','district_id' => '15','name' => NULL,'bn_name' => 'শাহমাখদুম','code' => '3312','url' => NULL),
  array('id' => '531','district_id' => '14','name' => NULL,'bn_name' => 'মাঝিরা','code' => '3712','url' => NULL),
  array('id' => '532','district_id' => '12','name' => NULL,'bn_name' => 'সলঙ্গা','code' => '3910','url' => NULL),
  array('id' => '533','district_id' => '12','name' => NULL,'bn_name' => 'এনায়েতপুর','code' => '3911','url' => NULL),
  array('id' => '534','district_id' => '13','name' => NULL,'bn_name' => 'আমিনপুর','code' => '4010','url' => NULL),
  array('id' => '535','district_id' => '27','name' => NULL,'bn_name' => 'খুলনা','code' => '4901','url' => NULL),
  array('id' => '536','district_id' => '27','name' => NULL,'bn_name' => 'আরাংঘাটা','code' => '4903','url' => NULL),
  array('id' => '537','district_id' => '27','name' => NULL,'bn_name' => 'দৌলতপুর','code' => '4904','url' => NULL),
  array('id' => '538','district_id' => '27','name' => NULL,'bn_name' => 'খানজাহান আলী','code' => '4911','url' => NULL),
  array('id' => '539','district_id' => '27','name' => NULL,'bn_name' => 'খালিশপুর','code' => '4912','url' => NULL),
  array('id' => '540','district_id' => '27','name' => NULL,'bn_name' => 'সোনাডাঙ্গা','code' => '4914','url' => NULL),
  array('id' => '541','district_id' => '27','name' => NULL,'bn_name' => 'লবণছড়া','code' => '4916','url' => NULL),
  array('id' => '542','district_id' => '27','name' => NULL,'bn_name' => 'হরিণটানা','code' => '4917','url' => NULL),
  array('id' => '543','district_id' => '25','name' => NULL,'bn_name' => 'করিমপুর','code' => '5407','url' => NULL),
  array('id' => '544','district_id' => '21','name' => NULL,'bn_name' => 'পাটকেলঘাটা','code' => '5505','url' => NULL),
  array('id' => '545','district_id' => '26','name' => NULL,'bn_name' => 'রহমতপুর','code' => '5604','url' => NULL),
  array('id' => '546','district_id' => '33','name' => NULL,'bn_name' => 'কাজিরহাট','code' => '5910','url' => NULL),
  array('id' => '547','district_id' => '34','name' => NULL,'bn_name' => 'শশীভূষণ','code' => '6207','url' => NULL),
  array('id' => '548','district_id' => '34','name' => NULL,'bn_name' => 'দুলারহাট','code' => '6209','url' => NULL),
  array('id' => '549','district_id' => '32','name' => NULL,'bn_name' => 'উজিরপুর','code' => '6303','url' => NULL),
  array('id' => '550','district_id' => '36','name' => NULL,'bn_name' => 'তামাবিল','code' => '2502','url' => NULL),
  array('id' => '551','district_id' => '36','name' => NULL,'bn_name' => 'মোগলাবাজার','code' => '2515','url' => NULL),
  array('id' => '552','district_id' => '36','name' => NULL,'bn_name' => 'শাহপরান','code' => '2516','url' => NULL),
  array('id' => '553','district_id' => '39','name' => NULL,'bn_name' => 'কোম্পানীগঞ্জ','code' => '2612','url' => NULL),
  array('id' => '554','district_id' => '38','name' => NULL,'bn_name' => 'শায়েস্তাগঞ্জ','code' => '2802','url' => NULL),
  array('id' => '555','district_id' => '59','name' => NULL,'bn_name' => 'পরশুরাম','code' => '4109','url' => NULL),
  array('id' => '556','district_id' => '59','name' => NULL,'bn_name' => 'তাজহাট','code' => '4110','url' => NULL),
  array('id' => '557','district_id' => '8','name' => NULL,'bn_name' => 'চট্টগ্রাম মহানগর','code' => '0101','url' => NULL),
  array('id' => '558','district_id' => '8','name' => NULL,'bn_name' => 'ভূজপুর','code' => '0104','url' => NULL),
  array('id' => '559','district_id' => '8','name' => NULL,'bn_name' => 'জোরারগঞ্জ','code' => '0117','url' => NULL),
  array('id' => '560','district_id' => '8','name' => NULL,'bn_name' => 'আকবরশাহ','code' => '0119','url' => NULL),
  array('id' => '561','district_id' => '8','name' => NULL,'bn_name' => 'সন্দ্বীপ','code' => '0120','url' => NULL),
  array('id' => '562','district_id' => '8','name' => NULL,'bn_name' => 'পাহাড়তলী','code' => '0121','url' => NULL),
  array('id' => '563','district_id' => '8','name' => NULL,'bn_name' => 'বাকলিয়া','code' => '0122','url' => NULL),
  array('id' => '564','district_id' => '8','name' => NULL,'bn_name' => 'চকবাজার','code' => '0123','url' => NULL),
  array('id' => '565','district_id' => '8','name' => NULL,'bn_name' => 'খুলশী','code' => '0124','url' => NULL),
  array('id' => '566','district_id' => '8','name' => NULL,'bn_name' => 'চাঁদগাও','code' => '0125','url' => NULL),
  array('id' => '567','district_id' => '8','name' => NULL,'bn_name' => 'পতেঙ্গা','code' => '0126','url' => NULL),
  array('id' => '568','district_id' => '32','name' => NULL,'bn_name' => 'পিরোজপুর সদর','code' => '6301','url' => NULL),
  array('id' => '569','district_id' => '8','name' => NULL,'bn_name' => 'বায়েজিদ','code' => '0129','url' => NULL),
  array('id' => '570','district_id' => '8','name' => NULL,'bn_name' => 'হালিশহর','code' => '0130','url' => NULL),
  array('id' => '572','district_id' => '9','name' => NULL,'bn_name' => 'ঈদগাহ','code' => '0209','url' => NULL),
  array('id' => '573','district_id' => '8','name' => NULL,'bn_name' => 'পাঁচলাইশ','code' => '0131','url' => NULL),
  array('id' => '574','district_id' => '47','name' => NULL,'bn_name' => 'হাজারীবাগ','code' => '1202','url' => NULL),
  array('id' => '575','district_id' => '47','name' => NULL,'bn_name' => 'সুত্রাপুর','code' => '1203','url' => NULL),
  array('id' => '576','district_id' => '47','name' => NULL,'bn_name' => 'সবুজবাগ','code' => '1204','url' => NULL),
  array('id' => '577','district_id' => '47','name' => NULL,'bn_name' => 'শ্যামপুর','code' => '1205','url' => NULL),
  array('id' => '578','district_id' => '47','name' => NULL,'bn_name' => 'শেরেবাংলা নগর','code' => '1206','url' => NULL),
  array('id' => '579','district_id' => '47','name' => NULL,'bn_name' => 'শাহবাগ','code' => '1207','url' => NULL),
  array('id' => '580','district_id' => '47','name' => NULL,'bn_name' => 'শাহআলী','code' => '1208','url' => NULL),
  array('id' => '581','district_id' => '47','name' => NULL,'bn_name' => 'লালবাগ','code' => '1209','url' => NULL),
  array('id' => '582','district_id' => '47','name' => NULL,'bn_name' => 'রামপুরা','code' => '1210','url' => NULL),
  array('id' => '583','district_id' => '47','name' => NULL,'bn_name' => 'রমনা','code' => '1211','url' => NULL),
  array('id' => '584','district_id' => '47','name' => NULL,'bn_name' => 'মোহাম্মদপুর','code' => '1213','url' => NULL),
  array('id' => '585','district_id' => '47','name' => NULL,'bn_name' => 'বিমান বন্দর','code' => '1216','url' => NULL),
  array('id' => '586','district_id' => '47','name' => NULL,'bn_name' => 'বাড্ডা','code' => '1217','url' => NULL),
  array('id' => '587','district_id' => '47','name' => NULL,'bn_name' => 'পল্টন','code' => '1220','url' => NULL),
  array('id' => '588','district_id' => '47','name' => NULL,'bn_name' => 'নিউমার্কেট','code' => '1221','url' => NULL),
  array('id' => '589','district_id' => '47','name' => NULL,'bn_name' => 'ধানমন্ডি','code' => '1222','url' => NULL),
  array('id' => '590','district_id' => '47','name' => NULL,'bn_name' => 'দক্ষিণখান','code' => '1224','url' => NULL),
  array('id' => '591','district_id' => '47','name' => NULL,'bn_name' => 'তেজগাঁও শিল্পাঞ্চল','code' => '1225','url' => NULL),
  array('id' => '592','district_id' => '47','name' => NULL,'bn_name' => 'তেজগাঁও','code' => '1226','url' => NULL),
  array('id' => '593','district_id' => '47','name' => NULL,'bn_name' => 'চকবাজার','code' => '1229','url' => NULL),
  array('id' => '594','district_id' => '47','name' => NULL,'bn_name' => 'গেন্ডারিয়া','code' => '1230','url' => NULL),
  array('id' => '595','district_id' => '47','name' => NULL,'bn_name' => 'খিলগাঁও','code' => '1232','url' => NULL),
  array('id' => '596','district_id' => '47','name' => NULL,'bn_name' => 'কলাবাগান','code' => '1237','url' => NULL),
  array('id' => '597','district_id' => '47','name' => NULL,'bn_name' => 'উত্তরা','code' => '1239','url' => NULL),
  array('id' => '598','district_id' => '13','name' => NULL,'bn_name' => 'আতাইকুলা','code' => '4011','url' => NULL),
  array('id' => '599','district_id' => '15','name' => NULL,'bn_name' => 'কাটাখালী','code' => '3313','url' => NULL),
  array('id' => '600','district_id' => '8','name' => NULL,'bn_name' => 'ই.পি.জেড','code' => '0128','url' => NULL),
  array('id' => '601','district_id' => '34','name' => NULL,'bn_name' => 'তজুমদ্দিন','code' => '6210','url' => NULL),
  array('id' => '602','district_id' => '1','name' => NULL,'bn_name' => 'সদর দক্ষিণ','code' => '1017','url' => NULL),
  array('id' => '603','district_id' => '47','name' => NULL,'bn_name' => 'হাতিরঝিল','code' => '1249','url' => NULL),
  array('id' => '604','district_id' => '33','name' => NULL,'bn_name' => 'কাউনিয়া','code' => '5912','url' => NULL),
        );

        DB::table('areas')->insert($areas);
    }
}
