<x-Form::select
    small="{{$small??''}}"
    name="area_id"
    class="select2"
    :default="$default??[]"
    placeholder="{{__('page.choose_option')}}"
    label="{{__('page.area')}}"
    :options="$areas"
/>
